### ISSUE TITLE
Create cache folder with correct permissions

### ISSUE THREAD

**Issue by ford--prefect** [89z/googleplay#1]
When first running, the folder ~/.cache/googleplay is created with 000 permissions, where it should be 775 (or similar).

**Comment by 89z** [comment]
Im on Windows, so I dont really have to deal with that stuff. At any rate, I think this is fixed with https://github.com/89z/googleplay/commit/fc489298bfa64c8d8f6baa24a69f6711ca3dbd31 - if its still not working, let me know.

Thanks!

**Comment by ford--prefect** [comment]
Building and testing with 1.3.1 yields no success, issue persists. Is this commit included in the release?

**Comment by 89z** [comment]
I am going to reopen this, but I guess I dont know how to fix it:

https://github.com/89z/googleplay/blob/bb9c9f2e4d7ea265e664f069f2f3a55f7f6f2151/cmd/googleplay/play.go#L147

**Comment by 89z** [comment]
Since the folder was already made wrong, you might have to delete it before the program will work again. Sorry I cant provide much help here, as I am on Windows.

**Comment by ford--prefect** [comment]
Thanks, I will look into this in the next days and make a MR when I have a solution.

**Comment by ford--prefect** [comment]
Ok, issue solved. While your commit  bb9c9f2 solved it, it was not included in 1.3.1 (but only 1.3.2).

**Comment by 89z** [comment]
That commit doesnt have any changes to `Mkdir`, but if it worked for you, then good.

Also stay tuned, I am going to be improving the default device today or tomorrow - I noticed that Instagram wasnt working.

**Comment by ford--prefect** [comment]
Right, that was 4802eae. My bad.
