### ISSUE TITLE
New Switches 

### ISSUE THREAD

**Issue by BrunoFischerGermany** [89z/googleplay#10]
Hello Again, 
I have nine a suggestion for your program googleplay.

How would it be if you use the switches 

--num-downloads - only the number of downloads will be output
--size-human - Only the size will be output (human readable- KB or MB)
--size-byte - Only the size will be printed (in bytes)
--title - Only the title will be printed (string)
--version-code - Only the version code will be output (string)
--version-string - Only the version string will be printed

Can you also get the date of the update?
--version-update-timestamp - e.g. UNIX timestamp or date/time

Further it would be cool to have a switch to get the previous version and previous-previous version. e.g. by another switch.
--pre or just --pre-pre

e.g. 
googleplay -a com.app.id --pre --version-code 
Return only: e.g. 20222381584

or 

googleplay -a com.app.id --pre-pre --version-string
Return only: e.g. 2.3.1

do you understand what i mean? What are the suggestions?

Greets Bruno

**Comment by 89z** [comment]
See here:

https://github.com/89z/googleplay/tree/master/docs#will-you-add-features

If you are willing to make a donation as documented there, then let me know. Thanks.

**Comment by BrunoFischerGermany** [comment]
Yes! Let me do an Donation. 
PayPal mabye?

**Comment by 89z** [comment]
My PayPal is `srpen6@gmail.com`

**Comment by 89z** [comment]
https://www.paypal.com/donate/?hosted_button_id=UEJBQQTU3VYDY

**Comment by 89z** [comment]
Thank you, I received the donation. However since this will take at least 1-2 hours to implement, I am asking for a $99 donation. Normally I would do the feature for free, but at this time I do not have a job, so I must ask for donation to implement this feature. If that is not acceptable, I can return the donation sent to me, thanks.

**Comment by BrunoFischerGermany** [comment]
hi. 
none of this is that important. i can solve this in another way. 
You can keep the 20 USD. 

I still have a question about Samsung Apps.

Have a look at com.sec.android.app.launcher. I get VersionCode 0, because there is no Samsung device stored.

Greetings

**Comment by 89z** [comment]
FYI I was able to fix `com.google.android.projection.gearhead.phonescreen`, but not the other one. However raccoon4 cant get it either, so the issue is not specific to this repo.
