### ISSUE TITLE
Downloaded APK Not Working in Real Android Device

### ISSUE THREAD

**Issue by mkamranmazhar** [89z/googleplay#101]
Thanks For Amazing Tool.

This Tools is Working Perfect from my end but the issue is this APK File Not working in Real Android Device.

i also tested and Downloaded the same name APK File from Online APK Downloader like evozi & its Working/installing in Real Android Device.

So let me know regarding this issue.

**Comment by 89z** [comment]
https://github.com/89z/googleplay#business

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/103

**Comment by 89z** [comment]
please provide example app

**Comment by mkamranmazhar** [comment]
com.facebook.lite
org.videolan.vlc
com.pinterest

All Brand Apps not install.
Please test i will send you more list of Apps.

Regards.

**Comment by 89z** [comment]
please confirm your device platform

- arm64-v8a
- x86
- armeabi-v7a
- other

**Comment by mkamranmazhar** [comment]
please confirm your device platform?

Did You mean by Mobile Device?
i already tested with 3 Different Android Mobile Phone Devices.

Regards.

**Comment by 89z** [comment]
please provide the native platform of the Android device, from the list above. I will not ask again.

**Comment by 89z** [comment]
https://play.google.com/store/apps/details?id=com.liuzh.deviceinfo

**Comment by mkamranmazhar** [comment]
Thank You for Providing me URL.
i also send you details SS via discord.

Platform : qcom

**Comment by 89z** [comment]
nope. Its listed under SOC, ABI

**Comment by mkamranmazhar** [comment]
Okay,
Yes You are right.
it's : arm64-v8a

**Comment by 89z** [comment]
default ABI is x86:

~~~
-p int
     nativePlatform
     0: x86
     1: armeabi-v7a
     2: arm64-v8a
~~~

So if you want a different one, you need to use the correct argument:

~~~
googleplay -a com.facebook.lite -p 2
~~~

**Comment by mkamranmazhar** [comment]
Thanks For the update.

APK Downloaded successfully with this argument -p 2
but another error in real device ( Parse Error ) There was a problem while parsing the package.
this time error changed.

**Comment by 89z** [comment]
Sorry, I am not able to emulate ARM devices, so I cannot help you. If anyone know how to do this with Android Studio, then we can continue. Otherwise, good luck to you.

**Comment by mkamranmazhar** [comment]
Again Thanks for the update.
Please do not mind but the issue is not resolved for what i paid?

as per your commitment i process the paypal and before process i make sure All APK Will Be Work? Here is Your Answers.
yes no problem - I can fix the issue

**Comment by 89z** [comment]
sorry for the trouble, but unless I can emulate ARM, then I cannot help to fix the issue. Currently I can only emulate x86 and x86_64, because of limitations with Android Studio. I will keep your donation, and if you have issue in the future I can provide service at no charge. Or if you know a way to emulate ARM with Android Studio, then I can help with this issue.

**Comment by mkamranmazhar** [comment]
Again Thanks for the update.
Please visit this URL : apps.evozi.com/apk-downloader/
All APK From this Provider is Working %100 Fine with ARM Devices.
So that mean it's possible to resolve this issue & You may also Search Google ( emulate ARM with Android Studio ) lot's of information available.

i am basically PHP Developer so don't have much experience in Android Studio.

**Comment by mkamranmazhar** [comment]
Please let me know update.
Have you fixed the issue?

**Comment by 89z** [comment]
I am sorry for your waiting. I recently started a new job, so I don't have as much free time as I used to. If you are still interested to continue, I will need an additional 80 USD. If you do not wish to continue, I can refund the current payment right away. Thanks and sorry again.

**Comment by mkamranmazhar** [comment]
additional 80 USD ?
what you will offer in this price ?
All APK Work on All Devices ?
All APK must be latest version which is available on Google Play Store ?
Example Add Feature to Download the Current APK Version From Play Store.

Do You also Add multi jobs? example Your tool work only 1 time 1 job.
Example:  not possible to download the 2 APK at single time only 1 APK at a time when its finish then 2nd.
but i want multi APK download feature at the same time in this tool.

i will pay 80 USD let me know if you confirm.

**Comment by mkamranmazhar** [comment]
Dear Steven Penny,

i am still waiting for Your update.

**Comment by 89z** [comment]
please be patient - I fell very sick this morning - so I am trying to get better - hopefully I can give you a full response later today

**Comment by mkamranmazhar** [comment]
first of all get well soon.
and thanks for the update i will wait no problem.

stay healthy and keep update.

**Comment by 89z** [comment]
> additional 80 USD ?

yes

> what you will offer in this price ?

I offer to solve the original posted issue

> All APK Work on All Devices ?

this is not possible, for example ARM APK will not work on some x86 devices. However assuming the APK platform matches the device platform, then yes

> All APK must be latest version which is available on Google Play Store ?

yes

> Example Add Feature to Download the Current APK Version From Play Store.

current program requires user to input version number, which can be obtained using details command. If you are requesting a new feature, it would be an additional charge.

> Do You also Add multi jobs? example Your tool work only 1 time 1 job.
> Example: not possible to download the 2 APK at single time only 1 APK at a time when its finish then 2nd.
> but i want multi APK download feature at the same time in this tool.

current program downloads one file at a time. If you are requesting a new feature, it would be an additional charge.

**Comment by mkamranmazhar** [comment]
Thanks For Your Update.
i can pay final 80 USD no more additional charge.

All APK Work on All Devices ?
All APK must be latest version which is available on Google Play Store ?
Example Add Feature to Download the Current APK Version From Play Store.

Do You also Add multi jobs? example Your tool work only 1 time 1 job.
Example: not possible to download the 2 APK at single time only 1 APK at a time when its finish then 2nd.
but i want multi APK download feature at the same time in this tool.

IF You Think 80 USD Enough for this Then Please let me know otherwise Please Refund Last 19USD.

Best Regards.

**Comment by 89z** [comment]
I have refunded the original payment. With all due respect, you are not making much sense with you comments, so I dont want to deal with this anymore. Good luck to you.
