### ISSUE TITLE
INSTALL_FAILED_NO_MATCHING_ABI

### ISSUE THREAD

**Issue by CStyleIO** [89z/googleplay#102]
example

adb: failed to install C:\Users\X\Downloads\googleplay-master\googleplay-master\cmd\googleplay\com.microsoft.skydrive-2026610103.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]

**Comment by 89z** [comment]
https://github.com/89z/googleplay#business
