### ISSUE TITLE
uploadDate not found, try another platform

### ISSUE THREAD

**Issue by IamDopey** [89z/googleplay#104]
Hello! In many applications it keeps giving me the error below and I don't know how to solve it:

POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.roblox.client
panic: uploadDate not found, try another platform

goroutine 1 [running]:
main.main()
	~/googleplay/cmd/googleplay/main.go:75 +0x505

**Comment by 89z** [comment]
https://github.com/89z/googleplay#business

**Comment by IamDopey** [comment]
What does that mean, "uploadDate not found, try another platform"?

**Comment by 89z** [comment]
I only provide paid support for issues

**Comment by dzervas** [comment]
@iamd0pey I think that you have to `-purchase` the specific app first for it to work. Worked for me at least
