### ISSUE TITLE
Downloading different abis

### ISSUE THREAD

**Issue by neervanbiqs** [89z/googleplay#106]
How to download a specific abi, eg x86_64? x86 downloaded by default.
Is it possible to download the whole apk file instead of splitted?

**Comment by jayluxferro** [comment]
@neervanbiqs use the following combination.

```
-s -p 0
```

This is the full usage:
```
Usage of googleplay:
  -a string
    	app
  -device
    	create device
  -email string
    	your email
  -p int
    	nativePlatform
    	0: x86
    	1: armeabi-v7a
    	2: arm64-v8a (default 2)
  -password string
    	your password
  -s	single APK (default true)
  -v uint
    	app version
  -verbose
    	verbose
```

**Comment by neervanbiqs** [comment]
Thanks! And if I need exactly x86_64 version?

**Comment by jayluxferro** [comment]
Assuming the bundle url is `com.netflix.mediaclient` and the version is `50282` then this is the command to get the x86 version. 

```
googleplay -a com.netflix.mediaclient -s -p 0 -v 50282
```

**Comment by neervanbiqs** [comment]
Yes, it is x86, I understand. But I need to download exactly x86_64, not x86.
I found that if I exec command googleplay -a "apk" -s (without -p) it downloaded the universal package that contains all abis so I could install --abi x86_64. But the size of the package is much bigger.

**Comment by neervanbiqs** [comment]
And unfortunately not all apk downloaded universal

**Comment by jayluxferro** [comment]
I get you now.

**Comment by 89z** [comment]
@jayluxferro I appreciate that you're a sponsor, but unless you wish to raise your contribution by a factor of 10, your actions here are not acceptable. See here:

https://github.com/89z/googleplay#money

**Comment by jayluxferro** [comment]
Well noted

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/110
