### ISSUE TITLE
panic: open /Users/user/googleplay/x86.bin: no such file or directory

### ISSUE THREAD

**Issue by NazariiStrohush** [89z/googleplay#110]
Hi! I'm using Macbook M1 and trying to get info and download apps.
<img width="862" alt="image" src="https://user-images.githubusercontent.com/17307937/200928433-118d33b8-2ab8-42f9-b40c-04fc69b1c51a.png">

**Comment by NazariiStrohush** [comment]
Thanks a lot!

**Comment by 89z** [comment]
@iamDonkey I charge for support:

https://github.com/89z/googleplay#money

so unless you want to sponsor me, I suggest you don't do that again. You've been warned.
