### ISSUE TITLE
Getting exception trying to create token file for account

### ISSUE THREAD

**Issue by Hainish** [89z/googleplay#112]
I'm getting an exception when trying to create token file for the account with the credentials you sent me (relates to https://github.com/EFForg/apkeep/issues/9)

```bash
user@go:~/googleplay-master/cmd/googleplay$ ./googleplay -email EMAIL -password PASSWORD
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
	/home/user/googleplay-master/cmd/googleplay/main.go:53 +0x5b0
```

**Comment by 89z** [comment]
I usually only provide paid support [1], but given the circumstance I am going to allow this one. Using current master, I get expected result:

~~~
> googleplay -email srpen6@gmail.com -password PASSWORD
POST https://android.googleapis.com/auth
~~~

Note also as mentioned on the main page [2]:

> Before trying these examples, make sure the Google account you are using has logged into the Play Store at least once before. Also you need to have accepted the Google Play terms and conditions.

If you're trying the account I sent you, I don't think I ever did that. So you will need to complete those steps first.



1. https://github.com/89z/googleplay#money
2. https://github.com/89z/googleplay#tool-examples

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/114

**Comment by 89z** [comment]
looks like Google blocked you. From that email inbox:

> Critical security alert
>
> Sign-in attempt was blocked 
>
> Someone just used your password to try to sign in to your account. Google blocked them, but you should check what happened.

so you need to get your own account somehow for testing.
