### ISSUE TITLE
 appCategory value not coming 

### ISSUE THREAD

**Issue by 89z** [89z/googleplay#116]
https://github.com/onyxbits/raccoon4/issues/115

**Comment by 89z** [comment]
fixed:

https://github.com/89z/googleplay/blob/3b3a9e07957f0d8988158f9ddb0b1d157d75d344/get_items.go#L15-L17

**Comment by 89z** [comment]
@Arshit007

**Comment by Arshit007** [comment]
Can you send the python code for the same or curl command?

**Comment by 89z** [comment]
I can send Go code, but not Python or cURL command.
