### ISSUE TITLE
panic: "Token" not found

### ISSUE THREAD

**Issue by andryan** [89z/googleplay#14]
Hi,

I managed to build the project but kept getting this error message:

POST https://android.clients.google.com/auth
panic: "Token" not found

goroutine 1 [running]:
main.main()
	temporary/googleplay-master/cmd/googleplay/main.go:34 +0x607

I have passed my email and password with -e and -p parameters respectively.

Any idea what I might have done wrong?

Thanks!

**Comment by 89z** [comment]
Please provide the exact command or commands you are using. I will reopen once that is done. Thank you!

**Comment by andryan** [comment]
I used the command as stated in the readme file:
googleplay -e EMAIL -p PASSWORD

**Comment by 89z** [comment]
Hm, this is a tough one, since I cant exactly get your full output, since password is involved. I am able to run everything fine using my account, also I checked Less Secure App Access [1], and it seems to work either way. I added a check for the response code [2], so you can try again with the latest commit if you want.


1. https://myaccount.google.com/lesssecureapps
2. https://github.com/89z/googleplay/commit/ece51a738d97bbbca64ffe8e0b199c52efaac8a7

**Comment by andryan** [comment]
Update: I have just enabled 2FA and created an app password, then I used the app password instead of the account's password.  It worked!  

$ googleplay -e email -p 'app password'
POST https://android.clients.google.com/auth
Create .cache/googleplay/token.json
$ googleplay -d
POST https://android.clients.google.com/auth
POST https://android.clients.google.com/checkin
POST https://android.clients.google.com/fdfe/uploadDeviceConfig
Sleeping 16s for server to process
Create .cache/googleplay/device.json

OOT: Interesting, for some reason after it worked, gplaycli is now also able to download using the same credentials.  Previously it kept giving this error message:
gpapi.googleplay.SecurityCheckError: 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password'

**Comment by 89z** [comment]
Glad to see you got it working. I am not using an app password myself, so I wouldnt think it would be needed. I am in the United States, are you as well?

**Comment by andryan** [comment]
I am in Indonesia.  I came across your project on gplaycli's GitHub.

I have cloned the latest git and I'm still getting the same error:
panic: "Token" not found

I used both wrong password and correct account password and got the same error.  Using the app password immediately creates the token.json file.

BTW, Less Secure App Access remains OFF for my Google account.

**Comment by 89z** [comment]
OK I added a warning about App Password. I am closing this now, any other issue let me know. Thanks!

**Comment by andryan** [comment]
Thanks for the tool and your support!

BTW, is there an option to download the full APK instead?  Or is there an easy way to merge the split APK files into an APK?

**Comment by 89z** [comment]
You can install a split like this:

https://github.com/89z/googleplay/tree/master/docs#how-to-install-split-apk

In regards to merging, I think thats beyond the scope of this project, but I might look into it. Also, did you ever try enabling Less Secure App Access as previously discussed? If that works, I think it is a better solution than App Password, as it doesnt require 2FA.

**Comment by andryan** [comment]
Yes.  I did enable it to test, but it didn't change the outcome.

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/20

**Comment by 89z** [comment]
FYI it seems it is possible to download a single APK, see linked issue. However I dont need that feature myself, so I would be wanting a donation to implement it.
