### ISSUE TITLE
install failed with error "INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113"

### ISSUE THREAD

**Issue by zuozhen** [89z/googleplay#15]
Hi,

This repo works great when download apk from GP. But it seems no any place to config device param. Now I face an issue that I couldn't install the app on my phone after download successfully. When I type "adb install xxxx.apk", there's an error "INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113".
What kind of device using to simulate to download app from GP, please?

My phone: IQOO Z1, arm64, Android 10.0
The app: I think it's not import for the app name. 
Hope can get help.

Thanks and regards,
Zuozhen

**Comment by 89z** [comment]
Yes, the module can control this here:

https://github.com/89z/googleplay/blob/855b6d9516fce61834db3f9932b51a3c8970183f/proto.go#L51-L58

However the tool does not currently have a way to control this. I can add this feature, but I require to know the app in question. I am closing for now, I will reopen once that question is answered. Thank you!

**Comment by cernec1999** [comment]
Hello,

I am attempting to get the `arm64-v8a` apk of `org.thoughtcrime.securesms`. Unfortunately, removing the two entries in the NativePlatform array below `arm64-v8a` does not seem to indicate the correct version that contains the needed binary. Is there some other step I need to take to ensure that the tool downloads arm64?

Chris

**Comment by cernec1999** [comment]
Here is more context to the error I'm having. Please see the attached screenshot, in which the Signal binary only contains binaries for x86.
![Screenshot from 2022-01-14 15-32-36](https://user-images.githubusercontent.com/5413945/149581407-19ae0afa-033d-4ac5-8da0-1b8c2a4ee29f.png)

**Comment by 89z** [comment]
> I am attempting to get the `arm64-v8a` apk of `org.thoughtcrime.securesms`.

Why do you need to do this? What is wrong with `x86`?

Unfortunately, removing the two entries in the NativePlatform array below `arm64-v8a` does not seem to indicate the correct version that contains the needed binary.

I dont understand this comment, as `arm64-v8a` is the last entry, so its not possible for any entries to be below the last entry.

> Here is more context to the error I'm having.

The correct way to do this is using `aapt`, for example:

https://github.com/89z/googleplay/blob/39b5a2d553ffc6669379cb3d2fc89f60512b881d/cmd/badging/badging.go#L17

**Comment by cernec1999** [comment]
> Why do you need to do this? What is wrong with x86?

I am using your tool to download apks for my native arm64 android device. I cannot use binaries that are x86 on my native arm device.

> I dont understand this comment, as arm64-v8a is the last entry, so its not possible for any entries to be below the last entry.

I was referring to the entries above `arm64-v8a`. My apologies. In any case, removing the entries above `arm64-v8a` do not seem to solve my problem.

**Comment by 89z** [comment]
> I am using your tool to download apks for my native arm64 android device. I cannot use binaries that are x86 on my native arm device.

OK, thats reasonable. However I do not like the manner in which this issue was posted. If you are willing to open a new issue, I can see about working on this.

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/18
