### ISSUE TITLE
Unable to download com.google.android.apps.walletnfcrel

### ISSUE THREAD

**Issue by sureshdsk** [89z/googleplay#16]
Thanks for the brilliant tool to download apks from playstore. 

I'm facing an issue when downloading `com.google.android.apps.walletnfcrel` 
Response:
```
Title: Google Pay
UploadDate:
VersionString:
VersionCode: 0
NumDownloads: 422.289 M
Size: 0 B
Offer: 0.00 USD
```
It is unable to get VersionCode.  Any help?

**Comment by 89z** [comment]
Should be fixed now:

https://github.com/89z/googleplay/blob/f27b0c3b9942030179d63e420fa4004aa5c22fb4/proto.go#L15-L16

**Comment by sureshdsk** [comment]
Thank you @89z  for the rapid response

**Comment by 89z** [comment]
@sureshdsk please star this repo if it is helpful
