### ISSUE TITLE
request for proxy support

### ISSUE THREAD

**Issue by sureshdsk** [89z/googleplay#17]
cli program doesn't seem to respect proxy configuration set via `HTTP_PROXY` and `HTTPS_PROXY` environment variables.

If you would like, I can add this feature and send PR if you guide me little bit. I'm new to golang and learning.

**Comment by 89z** [comment]
If you are willing to make donation, I will consider this feature. See here for more info:

https://github.com/89z/googleplay/tree/master/docs#will-you-add-features

**Comment by 89z** [comment]
I am reconsidering this suggestion. Do you have a source for good proxy?

**Comment by sureshdsk** [comment]
with good luck, we can find a working proxy ip here -> https://www.sslproxies.org. Usually after 3-5 attempts i get a working IP. It's not so fast. 
for paid/free trial I have tried http://proxymesh.com it works fast.

**Comment by 89z** [comment]
Sorry but that is not an acceptable response. I will do my own search, if I can't find anything, this issue will vbe closed again

**Comment by 89z** [comment]
In my case I am trying to get this app:

https://play.google.com/store/apps/details?id=air.ITVMobilePlayer

I found some UK proxies that work:

https://github.com/monosans/proxy-list

but even with those, I dont get that app with a search:

~~~
<nil> false 104.248.162.187:50761
<nil> false 159.65.88.184:43768
<nil> false 159.65.88.184:43768
<nil> false 178.62.22.215:19723
<nil> false 178.62.3.23:63253
<nil> false 178.62.32.105:54643
<nil> false 178.62.64.42:41423
<nil> false 178.62.79.49:15008
<nil> false 178.62.79.49:28113
<nil> false 178.62.79.49:35269
<nil> false 206.189.118.100:18938
<nil> false 212.38.189.118:35351
<nil> false 212.38.189.118:56668
<nil> false 46.101.5.73:48528
<nil> false 51.89.110.249:45678
~~~

which means that probably one of these headers is being checked as well:

~~~
Authorization
X-Dfe-Device-ID
~~~

**Comment by 89z** [comment]
OK I tried again using a GB `Authorization` and `X-Dfe-Device-ID` from here:

https://github.com/Juby210/gplayapi-go

as well as GB proxy, but still not getting the app to show up on a search. I guess it has something to do with the `aas_et` token, or maybe the proxy is leaking my true location. Either way, I am not writing proxy support if it wont allow me to get regional lockout apps. If anyone has an idea, I can look at this some more. Otherwise this is staying closed.
