### ISSUE TITLE
ARM Binary Download Support

### ISSUE THREAD

**Issue by cernec1999** [89z/googleplay#18]
Hello,

I am attempting to get the arm64-v8a apk of org.thoughtcrime.securesms. Unfortunately, removing the two entries in the NativePlatform array above arm64-v8a does not seem to indicate the correct version that contains the needed binary. Is there some other step I need to take to ensure that the tool downloads arm64?

Here is some additional context for my error.

New NativePlatform array:
```go
NativePlatform: []string{
    "arm64-v8a",
},
```
Wrong APK Pulled:
```sh
$ aapt dump badging org.thoughtcrime.securesms-98303.apk
... excluded for brevity ...
native-code: 'x86'
```

**Comment by 89z** [comment]
Closing this for now. If you are able to provide feedback, then I can reopen.

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/15

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/26

**Comment by 89z** [comment]
I am going to reopen this. I think I have a fix.

**Comment by 89z** [comment]
My mistake. My fix is for using ARM on x86, not for x86 on ARM.

**Comment by 89z** [comment]
I have an interest in fixing this now. I previously thought the `NativePlatform` logic was:

> iterate list in order, return first item offered by app

but is actually defined as:

> iterate list in order, return item with highest available version

So if you are fine with multiple platforms, and you have a preference, you must use separate devices, otherwise you wont be able to control what is returned.

**Comment by 89z** [comment]
This is fixed now:

https://github.com/89z/googleplay/blob/566eb767a252410ae2f71112c3db58653815ea35/cmd/googleplay/main.go#L14-L19

**Comment by 89z** [comment]
Example usage:

~~~
PS D:\Desktop> googleplay.exe -a org.thoughtcrime.securesms
Title: Signal Private Messenger
Creator: Signal Foundation
UploadDate: Apr 6, 2022
VersionString: 5.34.10
VersionCode: 103603
NumDownloads: 103.211 M
Size: 53.455 MB
Files: 1
Offer: 0 USD

PS D:\Desktop> googleplay.exe -a org.thoughtcrime.securesms -arm64
Title: Signal Private Messenger
Creator: Signal Foundation
UploadDate: Apr 6, 2022
VersionString: 5.34.10
VersionCode: 103602
NumDownloads: 103.211 M
Size: 52.235 MB
Files: 1
Offer: 0 USD
~~~
