### ISSUE TITLE
Unsupported protocol scheme

### ISSUE THREAD

**Issue by raffaem** [89z/googleplay#19]
I'm using git commit f4256a916024fbf2102bd081abcf924366daa11c.

I followed all the steps in the README, and I arrived at the last step where I download the app, where the following error is thrown:

```
$ ./googleplay -a com.a2a.energia -v 1524886976
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/delivery?doc=com.a2a.energia&vc=1524886976
GET 
panic: Get "": unsupported protocol scheme ""

goroutine 1 [running]:
main.main()
	[MYFOLDER]/googleplay/cmd/googleplay/main.go:57 +0x8a6
```

**Comment by 89z** [comment]
You dont just provide a random number to the version option, you need to provide a proper version:

~~~
PS C:\> googleplay -a com.a2a.energia
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.a2a.energia
Title: MyA2A
UploadDate: Jan 17, 2022
VersionString: 1.0.113
VersionCode: 113
NumDownloads: 4.545 K
Size: 27.825 MB
Offer: 0.00 USD

PS C:\> googleplay -a com.a2a.energia -v 113
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/delivery?doc=com.a2a.energia&vc=113
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0SarbDhq0zp6cGOwgbQ-KQbG6_Uj_uT3iyr5aVVcbIUvduehzUOFYf3jm7uiWnRJzw3fhSzfp7phYV1QAqLgJFIV__X9H4oJtws8ic3S58D_6iDfTo9BXMsMK-BLVPzgiKRz1SkLDAfBGqsHNMgCtPF_e4rPXBClxqm0BcOdhJCrEr37R2aMA2mRVqn99C8tEfoh4qf__o7VXCbIqKm541XM6gY5QzAgEztoxdU_CpfFzQZHvMTDSwYU8PRxqnqAltp1-dH7CNj-pbFBe59K-K9-BNjCTxPIq2MzlaBPnR4rTGFz_P8iI0FK3IXm9Fzo3Bp6KzP1W2DYjExZieSbnU_dJHCwiQv4LpwzxDccLIiHWcSayBkG9pghovfZUPtcz83sOmiRgOY_FUe&cpn=7q9t5RhZoNwrBkt0
~~~

However, I probably need to improve the error message, so I will leave this open for now.

**Comment by 89z** [comment]
OK I pushed a commit [1] that improves the error message:

~~~
PS C:\> googleplay -a com.a2a.energia -v 1524886976
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/delivery?doc=com.a2a.energia&vc=1524886976
panic: Version not found.
~~~

1. https://github.com/89z/googleplay/commit/c90e8838ed4e41e4b3be356d4f8096c0196eadaf

**Comment by raffaem** [comment]
Can we also improve README.md, specifying that after `-v` you need to provide the version code obtained in the previous passage?

**Comment by 89z** [comment]
I dont know why you would think that you could just use any random version code, or why you would think that the version code in the example would work with every single app. Regardless I updated the readme:

https://github.com/89z/googleplay/commit/7a0ccb039a8692c3bce19a22697373cc19e24f31

**Comment by raffaem** [comment]
> why you would think that the version code in the example would work with every single app

I didn't know that was a version code. I just copy and pasted the command from the README.

**Comment by 89z** [comment]
> I didn't know that was a version code.

All you had to do was run `googleplay` or `googleplay -h`:

~~~
googleplay [flags]
  -a string
        app
  -d    create device
  -e string
        email
  -o string
        output folder, must already exist
  -p string
        password
  -purchase
        Purchase app. Only needs to be done once per Google account.
  -v int
        version
  -verbose
        dump requests
~~~

> I just copy and pasted the command from the README.

This is just laziness. I have worked many months on this project, and you cant even be bothered to look at the help screen. I am blocking you from this project, I dont wish for you to waste any more of my time.
