### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by ford--prefect** [89z/googleplay#2]
From your readme the intended workflow is not immediately clear, e.g.:
- create token (bug #1)
- create device
- purchase app
- get download url by passing version (-a -v)

For the latter, it is not clear to me how to determine the correct version string. Maybe also add that to the doc.

**Comment by 89z** [comment]
This should be fixed with https://github.com/89z/googleplay/commit/7b10fc7d361745520a919dd5327e1afd7116b5a5 - if its still confusing let me know - I can try to improve it some more.

Thanks!

**Comment by 89z** [comment]
Also https://github.com/89z/googleplay/commit/99540965a7b0dff6928ebc55e08fc37c4c33145a

**Comment by 89z** [comment]
Also https://github.com/89z/googleplay/commit/9eb9df6ec9b0d6bd147d3c0a594280923c6eede7

**Comment by 89z** [comment]
Also https://github.com/89z/googleplay/commit/1362e25cded89fbfe8e2330b2678f1e386f2c826 (hopefully last commit)

**Comment by 89z** [comment]
Also https://github.com/89z/googleplay/commit/8e76545801cba38e1b01237b12e14e61b3479b64
