### ISSUE TITLE
Unable to download APK file

### ISSUE THREAD

**Issue by jayluxferro** [89z/googleplay#21]
Hi @89z, I tried your application but I'm unable to download the APK file. It shows "**Item not owned**".  A preview is shown below:

![Screenshot 2022-01-23 at 2 56 49 PM](https://user-images.githubusercontent.com/8394019/150684614-fdd7e4f8-7949-4c68-b27f-301d3c5a2d98.png)

**Comment by 89z** [comment]
I recently changed the error message, but it seems the new message is worse than the old one. I have changed it back:

https://github.com/89z/googleplay/commit/019001e297005e3c156bec6d7fa870179960cb29
