### ISSUE TITLE
Information incomplete, unable to download APK.

### ISSUE THREAD

**Issue by iambenmitchell** [89z/googleplay#22]
When the command runs, not all of the information is filled out. Because of this, I am unable to download the APK.

<img width="681" alt="image" src="https://user-images.githubusercontent.com/27426792/151604916-c3071df1-05a0-4be4-aafe-ceeac716f17a.png">

**Comment by 89z** [comment]
Should be able to use this alternative:

https://play.google.com/store/apps/details?id=com.hulu.plus

See here for more info:

https://github.com/89z/googleplay/tree/master/com#how-to-get-tv-apps

Closing this. If suggestion doesnt work for you, let me know and I can reopen.

**Comment by iambenmitchell** [comment]
I need the TV app, it is for my FireTV Stick. I ended up using something else anyways.

**Comment by 89z** [comment]
what did you use?
