### ISSUE TITLE
Can't run anything on Terminal

### ISSUE THREAD

**Issue by khaleelOrg** [89z/googleplay#24]
Below is my terminal command:
./googleplay -a com.google.android.youtube -v 1527109056

and here is the error: 
panic: EOF

goroutine 1 [running]:
main.main()
        /root/googleplay-master/cmd/googleplay/main.go:64 +0x685

@89z Please see the error, i am working on this repository but couldnt get any output.

**Comment by 89z** [comment]
Please specify what version you are using. I will reopen once thats done

**Comment by khaleelOrg** [comment]
@89z Thanks for your response. I have successfully configured and able to run your repository on my machine. One thing I was expecting from your project was support for region restricted apps but I have already seen this [issue#12](https://github.com/89z/googleplay/issues/12). 

One option left for me to download region restricted apps is to brute force all countries (locale) to googlePlay (by the way i am already using this repository: [NoMore201](https://github.com/NoMore201/googleplay-api)) on my website: [APKFuel.com](https://apkfuel.com/apk-downloader/). Once I solved Region Restricted issue on NoMore201, I will contribute to your project becuase [89z/googleplay/ ](https://github.com/89z/googleplay/) is just amazing.

**Comment by 89z** [comment]
> One thing I was expecting from your project was support for region restricted apps

It is possible to change the location, but I think you can only do it once per year:

https://github.com/89z/googleplay/tree/v1.7.4/docs#regional-lockout

Or if you have proxy. If you find another way, let me know.

> brute force all countries (locale) to googlePlay

What do you mean?

**Comment by khaleelOrg** [comment]
@89z If we already have gsfids and tokens specfic to every country, we can download region restricted apps, but the problem is how do we khow the specfic apk (for example: https://play.google.com/store/apps/details?id=com.sonyliv) is supported in which specific country? 

Google provides app passwords for developers, we can create as many app passwords as we want. I have a separate baby server which manages app passwords logins and generate gsfids (very similar to token-dispenser server if you know), A Vpn runs on my server, hence google can't block my ip. 

So here is some more detail: My main server just call playstore and download apks, The login call is based on gsfids and tokens (a file contains more than 50 gsfids and tokens), everytime my token expire, the main server just send a request to second server and this baby server just login with app passowrds and generate token and send it back to my Main server, hence I can play freely with GooglePlay api. 

The main problem is that how do we know the specific apk is supported in which specific region or the apk is blocked on which countries? 

Please let me know if you know something about this or provide me some hint.

**Comment by 89z** [comment]
I cant give more information, until you explain your process.

Assuming that you know the locale, for example I know this one is `en-GB`:

https://play.google.com/store/apps/details?id=air.ITVMobilePlayer

how am I able to download it? Once you can confirm that information, then I can answer your question.
