### ISSUE TITLE
Problems getting details information com.google.android.GoogleCamera

### ISSUE THREAD

**Issue by GRodrig** [89z/googleplay#25]
First run: ./googleplay -a com.google.android.GoogleCamera
```
Title: Câmara Google
UploadDate: 
VersionString: 
VersionCode: 0
NumDownloads: 1
Size: 0 B
Offer: 0.00 EUR
```

Second run: ./googleplay -a com.google.android.GoogleCamera -v 64764669
```
POST https://android.googleapis.com/auth
GET https://play-fe.googleapis.com/fdfe/delivery?doc=com.google.android.GoogleCamera&vc=64764669
panic: Geo-blocking
```

It could be several problems, but the main one I see is this app is only available for Google Devices aka Pixel
"Requirements - The latest version of Google Camera only works on Pixel phones running Android 12 and above."

I am not sure about how they check if it is a "Pixel" phone, but I would guess it's through the "[fingerprint parameter](https://github.com/NoMore201/googleplay-api/blob/master/gpapi/device.properties)".

By modifying the NoMore201 project, I was able to download this app with the latest version using a device with sdk=31 ("oriole" - Pixel 6).

**Comment by 89z** [comment]
Not sure why the heck you need to download that. As you can see from your own output, its literally only been downloaded one time, as it comes with every single Android already.

At any rate, its been fixed:

https://github.com/89z/googleplay/blob/b75079cbc18a674efe7b124ed33391bc733d1368/device.go#L35-L37
