### ISSUE TITLE
Single APK can not install on normal device

### ISSUE THREAD

**Issue by yetnelson** [89z/googleplay#26]
I downloaded single APK with `-s` flag reference issue #20.
```
googleplay -a com.shopee.id -v 583 -s
```
Yes, i got single APK which is more larger than split APKs. but it can not install in my android device and got err 
```
adb: failed to install tt.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
My device CPU is arm64 which supportedAbis is arm64-v8a;armeabi-v7a;armeabi.

I found the website apkcombo.com which provide APK download feature. I guess they also download the APK from gplay store api.

**Comment by 89z** [comment]
You should be able to change the code here:

https://github.com/89z/googleplay/blob/v1.8.0/device.go#L75-L82

I will see about maybe adding an option for this.

**Comment by 89z** [comment]
Actually, since it seems you already downloaded using  apkcombo.com, I am going to close this. If that is not the case let me know, and I can reopen.

**Comment by yetnelson** [comment]
> You should be able to change the code here:
> 
> https://github.com/89z/googleplay/blob/5027db53a111b1468c14bdde5b50c0312aa173d0/device.go#L75-L82
> 
> I will see about maybe adding an option for this.

Current the default NativePlatform already include `armeabi-v7a` and `arm64-v8a`. Does it means we need the APK which should supported both of the listed platforms?

I checked another device which sill install failure.
```
adb: failed to install com.shopee.id.apk: Failure [INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113]
```
here is the device info.
```
Linux localhost 4.9.117+ #1 SMP PREEMPT Wed Sep 16 18:28:51 WIB 2020 armv7l
```

**Comment by yetnelson** [comment]
I installed success in my armv7l device which specific `NativePlatforms = []string{"armabi-v7a"}`.
I just wonder what's the different between multiple platforms?

**Comment by 89z** [comment]
I do not wish to discuss this further. In the future, I would recommend not mentioning other websites, as it removing any motivation for me to make any changes. If you already downloaded using another website, then me changing anything is pointless.

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/18
