### ISSUE TITLE
Error: 403 Forbidden

### ISSUE THREAD

**Issue by kamushadenes** [89z/googleplay#27]
Hello, 

Thanks for the project! I have looked a lot for a Go alternative to gplaycli and was very happy when I found your project.

I'm having an issue though, even after creating an App Password, I'm receiving a 403.

Triple checked email and password, even tried my regular one to be sure, no avail.

Error happens during token creation:

```
                token, err = googleplay.NewToken(email, password)
		if err != nil {
			return err
		}
```

Since it doesn't use a *Device nor anything really configurable, I'm at a loss. Any idea what could be the problem?

My country is Brazil, if that matters, and the account is a Google Workspace one (but I'm the admin).

Thanks!

**Comment by kamushadenes** [comment]
This is the project I'm using it on

https://github.com/kamushadenes/apkrash

Specifically this file https://github.com/kamushadenes/apkrash/blob/main/store/main.go

**Comment by 89z** [comment]
Sorry, I can repro this. Using version v1.8.0 [1] with this code:

~~~go
package main
import "github.com/89z/googleplay"

func main() {
   token, err := googleplay.NewToken("srpen6@gmail.com", password)
   if err != nil {
      panic(err)
   }
   println(token.Token)
}
~~~

I get this result:

~~~
aas_et/AKppINbJpFuwhTdG9Uk-aUKWrn1sNL8EJUSZwCi2TMNLOUWGSTPv7gdgi3cDxoojvCGqu6...
~~~

You can try this older code:

~~~go
package main

import (
   "github.com/89z/format/crypto"
   "net/http"
   "net/http/httputil"
   "os"
   "net/url"
   "strings"
)

func main() {
   val := url.Values{
      "Email": {"srpen6@gmail.com"},
      "Passwd": {password},
      "sdk_version": {"20"},
   }.Encode()
   req, err := http.NewRequest(
      "POST", "https://android.googleapis.com/auth", strings.NewReader(val),
   )
   if err != nil {
      panic(err)
   }
   req.Header.Set("Content-Type", "application/x-www-form-urlencoded")
   hello, err := crypto.ParseJA3(crypto.AndroidAPI26)
   if err != nil {
      panic(err)
   }
   res, err := crypto.Transport(hello).RoundTrip(req)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   buf, err := httputil.DumpResponse(res, true)
   if err != nil {
      panic(err)
   }
   os.Stdout.Write(buf)
}
~~~

I get this result:

~~~
SID=BAD_COOKIE
LSID=BAD_COOKIE
services=mail,talk,cl,friendview,android,youtube,hist,googleplay,nova,sierra,multilogin,gerritcodereview,omaha,ahsid,mobile,cloudconsole,androiddeveloper,wise,billing,sitemaps,dynamite
Token=aas_et/AKppINaMtWwoPIAYk4imyBwnXDwDaeCO8CTxpKB2jLTfKN5tP5pr6HPsc_Kt_i_s...
~~~

1. https://github.com/89z/googleplay/tree/v1.8.0

**Comment by 89z** [comment]
closing for lack of response
