### ISSUE TITLE
-a cannot obtain app information

### ISSUE THREAD

**Issue by fzts** [89z/googleplay#29]
I am using an Indonesian account to download an app, but I cannot get the detailed information such as VersionCode, so I cannot download this app.
![image](https://user-images.githubusercontent.com/28336310/160360653-25e3b8db-0552-4ca7-adfc-7038edd5f461.png)

Thanks for the great program!

**Comment by 89z** [comment]
that is not a valid app:

https://play.google.com/store/apps/details?id=com.julofinance.juloapp

**Comment by fzts** [comment]
Please use the corresponding country's website to access
https://play.google.com/store/apps/details?id=com.btpn.dc&hl=en_US&gl=ID
