### ISSUE TITLE
Some apps can't be downloaded

### ISSUE THREAD

**Issue by HussamAlahmadi** [89z/googleplay#3]
Hi,

Thank you for your amazing  work.
However I found that some apps can't be downloaded as `com.infpro.infinityultraeditorpro`
as you can see below. 
I'm not sure what went wrong
```_
root@u:~/go/bin#_ ./googleplay -a 'com.infpro.infinityultraeditorpro' -v 2
POST /auth HTTP/1.1
Host: android.clients.google.com
Content-Type: application/x-www-form-urlencoded

GET /fdfe/delivery?doc=com.infpro.infinityultraeditorpro&vc=2 HTTP/1.1
Host: android.clients.google.com
Authorization: Bearer X
User-Agent: Android-Finsky (sdk=99,versionCode=99999999)
X-DFE-Device-ID: X

GET
panic: Get "": unsupported protocol scheme ""

goroutine 1 [running]:
main.main()
        /root/go/src/github.com/89z/googleplay/cmd/googleplay/main.go:51 +0x53f

**Comment by 89z** [comment]
Yeah, you have to purchase it first. I need to make a better error message :(

**Comment by 89z** [comment]
OK I made a better message:

~~~
PS C:\> googleplay -a com.infpro.infinityultraeditorpro -v 2
[...]
panic: 3 purchase required
~~~

If you have other problem let me know, thanks!

**Comment by 89z** [comment]
Also FYI, the `Authorization` and `X-DFE-Device-ID` headers are specific to your Google account, so I would probably edit them out. I might omit them from the output in the future, but for now its not a good idea to post the full strings.

**Comment by ford--prefect** [comment]
@89z Maybe configure the github issue workflow such that the danger of erroneously posting sensitive data is warned of before submission?

**Comment by 89z** [comment]
@ford--prefect in this case its not a huge deal. The `Authorization` expires in one hour anyway, and the Device isnt really your device, its just one that was created by the program. Im not sure if the device code works with any Google account, I would guess not.

**Comment by 89z** [comment]
FYI I have now added the cost as well (not pushed yet), so you can tell free app versus paid app:

~~~
PS C:\> googleplay -a com.cloudmosa.puffin
{Offer:{FormattedAmount:$4.99} Details:{AppDetails:{DeveloperName:CloudMosa Inc
VersionCode:51004300 Version:9.4.1.51004 InstallationSize:28849663
UploadDate:Oct 19, 2021}}}

PS C:\> googleplay -a com.vimeo.android.videoapp
{Offer:{FormattedAmount:$0} Details:{AppDetails:{DeveloperName:Vimeo.com, Inc.
VersionCode:3510004 Version:3.51.0 InstallationSize:37505533
UploadDate:Oct 22, 2021}}}
~~~

**Comment by sureshdsk** [comment]
I get this error when trying to download. any idea? 

```
googleplay -a com.google.android.youtube

&{InstallationSize:38.717 MB NumDownloads:10.860 B Offer:0.00 INR Title:YouTube VersionCode:1524493760 VersionString:16.46.37}
```

```
googleplay -a com.google.android.youtube -v 1524493760
GET
panic: Get "": unsupported protocol scheme ""

goroutine 1 [running]:
```

**Comment by 89z** [comment]
Yeah, I know about the problem. I have a fix here:

https://github.com/89z/googleplay/blob/965bb538356e1ea7e0254bf22e932a24f18883e6/research/2021-12-06/upload.go

I just got distracted with some other stuff. I will try to push a fix today

**Comment by 89z** [comment]
OK it looks like this is the problem:

~~~
android.software.leanback
~~~

its required by some apps, but breaks others. I have removed it for now, I will add it back when I figure out how to get it working. So the problem in the previous comment should be fixed now.

**Comment by sureshdsk** [comment]
yes it works now. thanks.

**Comment by 89z** [comment]
OK, seems the problem was, I was trying to get the TV app:

https://play.google.com/store/apps/details?id=com.iqiyi.i18n.tv

instead of the regular app:

https://play.google.com/store/apps/details?id=com.iqiyi.i18n

looks like TVs cant get any phone apps, and Phones cant get any TV apps. I could add a TV device, but probably not worth it
