### ISSUE TITLE
com.jackpocket cannot downloaded in US

### ISSUE THREAD

**Issue by xue5734** [89z/googleplay#36]
The  com.jackpocket cannot downloaded. Is there any way to deal with it

> googleplay -a com.jackpocket

panic: cannot unmarshal <nil> into field 2 of type protobuf.Varint

goroutine 1 [running]:
main.main()
        d:/work/googleplay/cmd/googleplay/main.go:73 +0x6f7

**Comment by 89z** [comment]
This should be fixed now on `master`:

~~~
PS C:\> googleplay -a com.jackpocket
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.jackpocket
Title: Jackpocket Lottery App
Creator: Jackpocket Inc.
UploadDate: Mar 21, 2022
VersionString: 2.11.8
VersionCode: 201
NumDownloads: 500.009 K
Size: 26.515 MB
Files: 4
Offer: 0 USD
~~~

**Comment by 89z** [comment]
please star this repo, if it is helpful
