### ISSUE TITLE
 server says: BadAuthentication

### ISSUE THREAD

**Issue by 89z** [89z/googleplay#37]
https://play.google.com/store/apps/details?id=org.mozilla.firefox

`github.com/matlink/gplaycli/issues/260`

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> googleplay -a org.mozilla.firefox
Title: Firefox Fast & Private Browser
Creator: Mozilla
UploadDate: Mar 30, 2022
VersionString: 99.1.1
VersionCode: 2015871917
NumDownloads: 330.968 M
Size: 89.238 MB
Files: 1
Offer: 0 USD
~~~

**Comment by 89z** [comment]
https://github.com/matlink/gplaycli/issues/260

**Comment by 89z** [comment]
@besendorf

**Comment by besendorf** [comment]
Thanks!

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/140

**Comment by 89z** [comment]
@NachumOlman

**Comment by 89z** [comment]
@muzzyrost

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/162

**Comment by 89z** [comment]
@marty0678

**Comment by 89z** [comment]
https://github.com/NoMore201/googleplay-api/issues/164

**Comment by 89z** [comment]
https://github.com/rehmatworks/gplaydl/issues/35

**Comment by 89z** [comment]
@qalekhani
