### ISSUE TITLE
panic: cannot unmarshal <nil> into field 2 of type protobuf.Varint

### ISSUE THREAD

**Issue by ashishov** [89z/googleplay#39]
Some apps give me the following error "cannot unmarshal <nil> into field 2 of type protobuf.Varint"

Examples with existing apps in the google play:
googleplay -a kr.sira.metal
googleplay -a la.droid.qr.priva
googleplay -a kr.sira.compass
googleplay -a kr.sira.measure
googleplay -a com.hamsterbeat.wallpapers.fx.panorama
googleplay -a br.com.rodrigokolb.realdrum

Examples which has to return 404, but it also returns "cannot unmarshal <nil> into field 2 of type protobuf.Varint"
googleplay -a com.mhoffs.customlocale
googleplay -a com.adobe.flashplayer

**Comment by 89z** [comment]
these are now fixed:

~~~
PS D:\Desktop> googleplay -a kr.sira.metal
Title: Metal Detector
Creator: Smart Tools co.
UploadDate: Mar 1, 2022
VersionString: 1.5.10
VersionCode: 64
NumDownloads: 19.079 M
Size: 5.663 MB
Files: 1
Offer: 0 USD

PS D:\Desktop> googleplay -a kr.sira.measure
Title: Smart Measure
Creator: Smart Tools co.
UploadDate: Mar 4, 2022
VersionString: 1.7.8
VersionCode: 76
NumDownloads: 42.637 M
Size: 5.649 MB
Files: 1
Offer: 0 USD

PS D:\Desktop> googleplay -a kr.sira.compass
Title: Smart Compass
Creator: Smart Tools co.
UploadDate: Feb 26, 2022
VersionString: 1.8.10
VersionCode: 91
NumDownloads: 34.183 M
Size: 6.076 MB
Files: 1
Offer: 0 USD
~~~

still working on these:

~~~
googleplay -a la.droid.qr.priva
googleplay -a com.mhoffs.customlocale
googleplay -a com.hamsterbeat.wallpapers.fx.panorama
googleplay -a com.adobe.flashplayer
~~~

**Comment by 89z** [comment]
Last update for this one is 2014:

~~~
googleplay -a com.adobe.flashplayer
~~~

why do you need it?

still working on these:

~~~
googleplay -a com.hamsterbeat.wallpapers.fx.panorama
googleplay -a com.mhoffs.customlocale
googleplay -a la.droid.qr.priva
~~~

**Comment by ashishov** [comment]
I have a base with Android Apps so I am trying to check if apps have any updates and download new version if so

**Comment by 89z** [comment]
Unless you can provide a good reason for this one:

~~~
googleplay -a com.adobe.flashplayer
~~~

I am not adding it. I am not support 8 year old APK, unless you have a good reason. Other ones I am still working on.

**Comment by 89z** [comment]
This one fixed:

~~~
PS D:\Desktop> googleplay -a com.hamsterbeat.wallpapers.fx.panorama
Title: Panoramic Screen
Creator: Hamster Beat
UploadDate: Jan 23, 2017
VersionString: 3.0.10
VersionCode: 38
NumDownloads: 2.244 M
Size: 5.857 MB
Files: 1
Offer: 0 USD
~~~

still working on these:

~~~
googleplay -a com.mhoffs.customlocale
googleplay -a la.droid.qr.priva
~~~

**Comment by 89z** [comment]
This one has last update 2016:

~~~
googleplay -a la.droid.qr.priva
~~~

need a good reason to support. still working on this one:

~~~
googleplay -a com.mhoffs.customlocale
~~~

**Comment by 89z** [comment]
Actually flash player has been pulled:

https://play.google.com/store/apps/details?id=com.adobe.flashplayer

so definitely not supporting that.

**Comment by 89z** [comment]
this one has been pulled:

https://play.google.com/store/apps/details?id=com.mhoffs.customlocale

closing now. If you have some justification for the ones I rejected, I will consider it. Otherwise this is done.

**Comment by 89z** [comment]
This one is fixed:

~~~
PS D:\Desktop> googleplay -a br.com.rodrigokolb.realdrum
Title: Real Drum: electronic drums
Creator: Kolb Apps
UploadDate: Apr 12, 2022
VersionString: 10.9.8
VersionCode: 245
NumDownloads: 122.293 M
Size: 60.134 MB
Files: 4
Offer: 0 USD
~~~
