### ISSUE TITLE
how do i use it

### ISSUE THREAD

**Issue by NTT1906** [89z/googleplay#4]
i tried to install it but it keeps failing 

`go install
~/go/googleplay $ ls
auth.go       device.go       go.mod       readme.md  token_test.go
auth_test.go  device_test.go  go.sum       research
cmd           docs            license.txt  token.go
~/go/googleplay $ go list
github.com/89z/googleplay
~/go/googleplay $ googleplay
googleplay: command not found
~/go/googleplay $ go packages
go packages: unknown command
Run 'go help' for usage.
~/go/googleplay $ go test
# github.com/89z/googleplay [github.com/89z/googleplay.test]
./token_test.go:11:32: undefined: password

FAIL    github.com/89z/googleplay [build failed]
~/go/googleplay $
~/go/googleplay $ ls
auth.go       device.go       go.mod       readme.md  token_test.go
auth_test.go  device_test.go  go.sum       research
cmd           docs            license.txt  token.go
~/go/googleplay $ go install
~/go/googleplay $ googleplay
googleplay: command not found
~/go/googleplay $ go get
go: downloading golang.org/x/sys v0.0.0-20210615035016-665e8c7367d1
~/go/googleplay $ googleplay
googleplay: command not found
~/go/googleplay $ go install
~/go/googleplay $ go help
Go is a tool for managing Go source code. `

**Comment by 89z** [comment]
You probably need to update your PATH. When you use `go install`, it goes here:

~~~
PS C:\> go env GOPATH
C:\Users\Steven\go
~~~

I am closing this, as its a Go issue, and not specific to this repo. Thanks!
