### ISSUE TITLE
How to set output directory?

### ISSUE THREAD

**Issue by vegedreamgagnoa** [89z/googleplay#40]
Hey @89z great work. I just wondering if there's any way for us to set the output directory?

**Comment by 89z** [comment]
please star this repository, and I will add the feature

**Comment by vegedreamgagnoa** [comment]
Thanks!

**Comment by vegedreamgagnoa** [comment]
Done - now add!!!!!!!!!!!!!!!! 👍

**Comment by 89z** [comment]
Hello, thanks for the star.

How based on the extremely rude nature of your last comment, I will only add the feature if you make a $99 donation. If you are interested to do that, let me know. Otherwise, please don't ever comment on this repository again.

**Comment by vegedreamgagnoa** [comment]
Wow, sorry - just kidding on that, it's okay if you don't want to add it. Great work though!
