### ISSUE TITLE
Not working app from android tv

### ISSUE THREAD

**Issue by VuzzyM** [89z/googleplay#43]
Is not working ./googleplay.exe -a 

This is android tv application com.boosteroidtv.streaming

https://play.google.com/store/apps/details?id=com.boosteroidtv.streaming&hl=en&gl=US

**Comment by 89z** [comment]
Yeah, I removed TV support recently, in favor of adding support for ARMEABI and ARM64. I am not sure if I want to add TV support back at this time. You can get the phone app:

~~~
PS C:\> googleplay -a com.boosteroid.streaming
Title: Boosteroid
Creator: Boosteroid
UploadDate: Apr 25, 2022
VersionString: v.1.2.10
VersionCode: 10210
NumDownloads: 211.420 K
Size: 10.943 MB
Files: 1
Offer: 0 USD
~~~

Is that acceptable?

**Comment by VuzzyM** [comment]
> Yeah, I removed TV support recently, in favor of adding support for ARMEABI and ARM64. I am not sure if I want to add TV support back at this time. You can get the phone app:
> 
> ```
> PS C:\> googleplay -a com.boosteroid.streaming
> Title: Boosteroid
> Creator: Boosteroid
> UploadDate: Apr 25, 2022
> VersionString: v.1.2.10
> VersionCode: 10210
> NumDownloads: 211.420 K
> Size: 10.943 MB
> Files: 1
> Offer: 0 USD
> ```
> 
> Is that acceptable?

Yes, this is it, please add this option back

**Comment by 89z** [comment]
> please add this option back

I am closing this for now. You just commanded me to do something, rather than ask. A polite command is still a command. I will now only add TV back if I personally want to, or if you decide to make a donation:

https://github.com/89z/googleplay/tree/v1.9.1/docs#will-you-add-features
