### ISSUE TITLE
Login failed

### ISSUE THREAD

**Issue by duyuphp** [89z/googleplay#47]
hello
googleplay -e xxx -p xxx 

POST https://android.googleapis.com/auth
panic: 403 Forbidden

**Comment by druphliu** [comment]
Yes,I am also facing the same issue from last day only.When did you start facing this same problem?

**Comment by 89z** [comment]
Good morning. I run ran the same command from `master`, with no problem. Make sure you have accepted the Google Play terms and conditions, before trying to use this tool:

https://github.com/89z/googleplay#tool-examples

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/79

**Comment by 89z** [comment]
@Arshit007

**Comment by 89z** [comment]
@adtimizer

**Comment by druphliu** [comment]
> 

How to accepted the Google Play terms and conditions?

**Comment by druphliu** [comment]
> Good morning. I just ran the same command from `master`, with no problem. Make sure you have accepted the Google Play terms and conditions, before trying to use this tool:
> 
> https://github.com/89z/googleplay#tool-examples

How to accepted the Google Play terms and conditions?

**Comment by 89z** [comment]
@shifoc can you help?

**Comment by 89z** [comment]
@cryptax can you help?

**Comment by shifoc** [comment]
@89z @druphliu @duyuphp you need to login from a phone or emulator on the playstore app and accept the terms and conditions

**Comment by shifoc** [comment]
A prompt will appear when you login

**Comment by adtimizer** [comment]
@89z Thanks for the reference. I've tried the suggested flow but i'm getting 
panic: 403 Forbidden
before using the email and password i've logged in to the playstore using emulator with the right email and password.
does the fact that my account uses 2FA changes anything? i also tried with app specific password but without any luck
appreciate your help here!

**Comment by 89z** [comment]
@adtimizer sorry I cant be much help here, as the command works for me. I would suggest trying to install a free app using the Play Store, with a real phone or emulator. Then after that, try the command again.

**Comment by adtimizer** [comment]
@89z your help so far is great!!!
It seems like when using an account without the 2FA it works.
now i'm stuck with 

panic: Purchase required

although i ran the command as you instructed. will see what's the reason.
Thanks again for your help so far

**Comment by 89z** [comment]
> panic: Purchase required

@adtimizer thats a different issue, you have to purchase apps, even free apps. Review the examples for more information:

https://github.com/89z/googleplay#tool-examples

**Comment by adtimizer** [comment]
@89z 
I've followed the instructions one by one but even after purchasing using the command -purchase i get the same error.
Would love to pay for your help here

**Comment by 89z** [comment]
@adtimizer please stay on topic. It seems you no longer have the login issue. If you have other issue, then post a new issue, or contact me privately. This issue is strictly for login problem.

**Comment by 89z** [comment]
https://github.com/rehmatworks/gplaydl/issues/33

**Comment by duyuphp** [comment]
@89z Thank you very much, I changed my account and it worked fine

**Comment by 89z** [comment]
OK I have updated the README again. Why people insist in using a brand new account for this is beyond me. Oh well.

**Comment by 89z** [comment]
@kronicd

**Comment by 89z** [comment]
@poseidonsg

**Comment by poseidonsg** [comment]
Thanks! I am using the python code here: https://github.com/NoMore201/googleplay-api . I have tested both your code and racoon. Both are working fine but I am not sure why the other one has stopped working.

**Comment by 89z** [comment]
@poseidonsg this is not the place to discuss other tools. If you have a problem with my tool, please comment. Otherwise don't.

**Comment by craftbyte** [comment]
Is it normal to get a 404 though?
```
POST https://android.googleapis.com/auth
panic: 404 Not Found

goroutine 1 [running]:
main.main()
        /home/anze/go/pkg/mod/github.com/89z/googleplay@v1.9.2/cmd/googleplay/main.go:53 +0x725
```

**Comment by 89z** [comment]
@craftbyte this issue is done, as far as I am concerned. If you're still having a problem, post a new issue.

**Comment by 89z** [comment]
https://github.com/ClaudiuGeorgiu/PlaystoreDownloader/issues/80

**Comment by 89z** [comment]
@kotko @cuongtobi

**Comment by Arshit007** [comment]
I am not able to login in the playstore.It is giving me 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password' again and again

**Comment by 89z** [comment]
Since people don't know how to read, I am locking this issue. As I said before, issue is resolved for author, so that's good enough for me. If you still have issue, post a new issue.

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/53

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/92
