### ISSUE TITLE
Why some app can't get version?

### ISSUE THREAD

**Issue by MrLuoXuan** [89z/googleplay#48]
For example package com.riotgames.league.wildrift, use ./google_play -a com.riotgames.league.wildrift

~~~
Raise error panic: cannot unmarshal <nil> into field 2 of type protobuf.Varint
~~~

Can you get versionCode from this app?

**Comment by 89z** [comment]
This APK is 1.699 GB:

https://apkmirror.com/apk/riot-games-inc/league-of-legends-wild-rift/league-of-legends-wild-rift-3-2-0-5531-release/league-of-legends-wild-rift-3-2-0-5531-2-android-apk-download

I am not interested to support something this large. I am closing this for now. If you are willing to make a donation, let me know, and I can add support for this APK:

https://github.com/89z/googleplay/tree/v1.9.2/docs#will-you-add-features

**Comment by 89z** [comment]
Correction. This does work, but you must request using ARM:

~~~
PS C:\> googleplay -a com.riotgames.league.wildrift -armeabi
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.riotgames.league.wildrift
Title: League of Legends: Wild Rift
Creator: Riot Games, Inc
UploadDate: Apr 25, 2022
VersionString: 3.2.0.5531
VersionCode: 553164
NumDownloads: 44.936 M
Size: 1.675 GB
Files: 5
Offer: 0 USD
~~~

**Comment by MrLuoXuan** [comment]
Thank you very much, my dear author.
I used -armeabi and i can get the version, but other package name com.ea.gp.apexlegendsmobilefps also can't get version, i try to use -armeabi and -arm64, can't get version.
I will do donate, but i'm finding the way to transfer my money to dollar, because i'm from china, do you have alipay or wechatPay?

[root@QY-AppDownloadProxy-HK ~]# ./google_play -a com.ea.gp.apexlegendsmobilefps -arm64
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.ea.gp.apexlegendsmobilefps
map[1:map[2:map[-21:map[14:[111 117 115]] 4:map[-9:map[5:9] 1:com.ea.gp.apexlegendsmobilefps 2:com.ea.gp.apexlegendsmobilefps 3:1 4:3 5:Apex Legends Mobile 6:ELECTRONIC ARTS 7:Set within the immersive Apex Legends™ universe, Apex Legends Mobile is a strategic battle royale shooter game that features Legendary character-based gameplay, best-in-class squad battles, and fast-paced combat that cemented the game’s place as one of the top shooters, all in a mobile package.<br><br>Players can join forces with two friends to compete with other mobile players, combining each Legend&#39;s unique skills to master team roles, synergize plays, and dominate the Apex Legends Games.<br><br>Battle Royale matches, Arena &amp; legendary squad play await. Download Apex Legends Mobile today!<br><br><b>APEX LEGENDS MOBILE FEATURES</b><br><br>Strategic Gameplay with Iconic Legends<br>- Strategic squad play and Battle Royale is the core of our DNA!<br>- Equip an arsenal of exotic weaponry, equipment, and tactical abilities<br>- Find the SMG, Assault Rifle, LMG, Shotgun, to fit your playstyle!<br>- Fast-paced strategic choices are essential in the Apex Legends arena<br>- Choose from a cast of beloved Legends as well as exclusive characters to the mobile version of the game<br>- Master each character with unique abilities and personalities to find a Legend that fits an array of playstyles<br><br>Team-based Multiplayer Hero Shooter<br>- Squad up with two other players in competitive PvP team games<br>- Create legendary squads by combining each teammates’ unique skillset<br>- Multiplayer squad play with strategic combinations and evolving tactics<br>- Dominate the battlefield! Join forces with friends and players alike in epic battle royale games<br><br>High-Octane Competition<br>- Fast-paced innovative PvP FPS &amp; TPS hero shooter combat gameplay<br>- Fluid movement and gunplay<br>- Exhilarating action that amplifies the mobile battle royale fun<br>- Rooted in an Immersive and Ever-Evolving Apex Legends Universe<br>- Unpredictable conditions and challenges<br>- New Legends are continuously introduced to test players’ skills<br><br>Mobile First Adaptations &amp; Innovations<br>- A standalone Apex Legends title on mobile<br>- Optimized UI and controls custom-built for mobile devices<br>- Unique mobile-only content and gameplay modes<br>- New Legends, maps, gameplay, modes, progression, and live events<br><br>Download today and become an Apex Legend!<br><br>Registration does not guarantee access to Apex Legends™ Mobile. Requires acceptance of (i) Pre-Release Feedback Agreement. Age restrictions apply. Gameplay progress, achievements, characters, character data and/or any other value or status indicators achieved in the limited territory launch will not transfer to World-wide launch. Apex Legends Mobile is a limited territory pre-release software, may contain errors/defects and is provided “as is” without any express or implied warranty.<br><br>This app: Requires acceptance of EA’s Privacy &amp; Cookie Policy and User Agreement. Requires a persistent Internet connection (network fees may apply). Includes in-game advertising.  Collects data through third-party ad-serving and analytics technology (See Privacy &amp; Cookie Policy for details). Contains direct links to the Internet and social networking sites intended for an audience over 13. Allows players to communicate. Includes optional in-game purchases of virtual currency that can be used to acquire virtual in-game items, including a random selection of virtual in-game items.The app uses Google Play Game Services.  Log out of Google Play Game Services before installation if you don’t want to share your game play with friends. <br><br>User Agreement: terms.ea.com<br>Privacy and Cookie Policy:  privacy.ea.com <br>Visit help.ea.com for assistance or inquiries.<br><br>Do Not Sell My Personal Information:  https://tos.ea.com/legalapp/WEBPRIVACYCA/US/en/PC/<br><br>EA may retire online features after 30 days’ notice posted on ea.com/service-updates. 8:map[1:0 2:HKD 3: 5:0 8:1 26:购买] 9:(         10:[map[1:2 5:https://play-lh.googleusercontent.com/8XT0BJlCa85KhTj0yLnMcXwiHZeHLmrkqZwmp0omrzROgi-rgJJp2CDYhIVpZFYWyw 9:1 15:#EBE9E4] map[1:4 5:https://play-lh.googleusercontent.com/8isS-YFm__fihisdZz0l0Sgg9QRmaxKSVfBD6HdiZzSiNXywTAiPb9hCafJT3WaToPA 9:1 15:#131012 25:1] map[1:3 5:https://www.youtube.com/watch?v=KWeZWERerNI&feature=youtu.be] map[1:13 5:https://i.ytimg.com/vi/KWeZWERerNI/hqdefault.jpg 9:0] map[1:1 5:https://play-lh.googleusercontent.com/oYtBLESvyD9SL1zigwwFsLvkkB3ZFXFtBt0pXtAVAi6m4NaL5lNGCmRTCnscchnCP-I 9:1] map[1:1 5:https://play-lh.googleusercontent.com/Pi1CzjrjfcE4O9FJuNOL3Dx7rXK542_mzp7YVQrTz9CcU-HAbPC08wCpXeImVf7olVw 9:1] map[1:1 5:https://play-lh.googleusercontent.com/hA3D_8YZ7Le3bW6f8Dt8gMWJuIaLbX-fQ_fkRKV6ogSA0xYJM-K51NRc6hhoKiiE4Z5G 9:1] map[1:1 5:https://play-lh.googleusercontent.com/7BIXNKRbddLvOd9mbU-Mq0FS6CJ-WiE-2qFttMphxQBLbEuFaj1hHP4J3p1vOfaIu58 9:1] map[1:1 5:https://play-lh.googleusercontent.com/cIlJJF3CwqUpsATaLNpONOFq_nhQXc5bHUaHkuxXEAzqw_oXGlxRb-8ObgKNRJc5d_Nx 9:1] map[1:1 5:https://play-lh.googleusercontent.com/45G7YSux_dDRR7RJbrHi3Ts7-UdeFra0rc4gw7p-gXjW75Woab3fZYS8o4HpefWz4Rad 9:1]] 13:map[1:map[1:ELECTRONIC ARTS 11:help@eamobile.com 12:https://www.ea.com/games/apex-legends/news/closed-beta-mobile-faq 13:超过5,000,000次下载 14:com.ea.gp.apexlegendsmobilefps 18:GAME 22:map[1:EvGYwThFBbWyZgEuPfDcwiXpy0M 2:W_99YU4boRpWartYnIY7AT95qnR70hRnMzZsViWl8NI] 45:Geneva, Switzerland 46:map[2:map[2:browseDeveloperPage?docid=developer-6605125519975771237]] 48:动作 53:5000000 61:500万+ 68:map[1:ELECTRONIC ARTS] 70:6956000 73:map[1:map[1:7 8:map[1:3]]] 75:map[1:map[1:7 8:map[1:17]]] 76:map[1:map[1:7 8:map[1:19]]] 77:500万 78:500万 82:map[1:map[1:因设备而异 2:手机]]]] 15:map[18:http://privacy.ea.com/en 29:map[1:12 岁以上 2:map[1:6 5:https://play-lh.googleusercontent.com/yQChfa9XKlaXMIYTk8w8QwChjT8_SH-_2d2SS-kesw0TLQK1nxtw54bDcoZ09freZJgKrtg4f__is-31Vg 9:1] 4:中度暴力<br/>用户交互, 游戏内购买（含随机项目）<br/><a href="https://support.google.com/googleplay?p=appgame_ratings">了解详情</a>] 53:map[1:GAME] 71:map[1:动作 2:map[2:map[2:homeV2?cat=GAME_ACTION&c=3]] 3:map[1:7 8:map[1:5]]] 72:[map[1:500万+ 3:下载次数 4:map[1:7 8:map[1:3]] 8:已下载超过 500万 次] map[2:map[1:6 5:https://play-lh.googleusercontent.com/yQChfa9XKlaXMIYTk8w8QwChjT8_SH-_2d2SS-kesw0TLQK1nxtw54bDcoZ09freZJgKrtg4f__is-31Vg 9:1] 3:12 岁以上 4:map[1:7 8:map[1:15]] 6:map[-5:map[1:https://support.google.com/googleplay?p=appgame_ratings] 1:map[1:6 5:https://play-lh.googleusercontent.com/YrkR-GP7OKghBTATCoO_jJrchSVrh-NSUBb5DnbRZC1DbLK_cgV9FC2e_iI4GzLsKXuZjuFZajnGCiA8qA 9:1] 2:中度暴力 3:用户交互, 游戏内购买（含随机项目） 5:
7https://support.google.com/googleplay?p=appgame_ratings] 8:内容分级：12 岁以上]] 80:apps/detailsLiveOpsStream?doc=com.ea.gp.apexlegendsmobilefps 85:promotion/detailsPagePromotion?doc=com.ea.gp.apexlegendsmobilefps 97:map[2:map[2:homeV2?cat=GAME_ACTION&c=3]] 102:map[1:map[1:7 8:map[1:5]]] 108:GAME_ACTION] 16:details?doc=com.ea.gp.apexlegendsmobilefps 17:https://play.google.com/store/apps/details?id=com.ea.gp.apexlegendsmobilefps 18:rev?doc=com.ea.gp.apexlegendsmobilefps&n=20 21:1 23:Apex Legends Mobile 以身临其境的 Apex Legends™ 世界为背景，是一款战略大逃杀射击游戏，具有基于传奇角色的游戏玩法、一流的小队战斗和快节奏的战斗，巩固了游戏作为顶级游戏之一的地位射手，都在一个移动包中。<br><br>玩家可以与两个朋友联手与其他移动玩家竞争，结合每个传奇的独特技能来掌握团队角色，协同比赛，并称霸 Apex 传奇游戏。<br><br>大逃杀比赛、竞技场和传奇小队比赛等待着您。立即下载 Apex Legends Mobile！<br><br><b>APEX 传奇移动版功能</b><br><br>具有标志性传奇的战略游戏<br>- 战略小队游戏和大逃杀是我们 DNA 的核心！<br>- 装备奇异的武器、装备和战术能力<br>- 找到适合您游戏风格的 SMG、突击步枪、LMG、霰弹枪！<br>- 在 Apex Legends 竞技场中，快节奏的战略选择至关重要<br>- 从一系列深受喜爱的传奇人物以及独家角色中选择移动版游戏<br>- 掌握具有独特能力和个性的每个角色，以找到适合各种游戏风格的传奇<br><br>基于团队的多人英雄射击游戏<br>- 在竞争激烈的 PvP 团队游戏中与其他两名玩家组队<br>- 通过结合每个队友的独特技能创建传奇小队<br>- 多人小队玩战略组合和不断发展的战术<br>- 称霸战场！在史诗般的大逃杀游戏中与朋友和玩家联手<br><br>高辛烷值竞争<br>- 快节奏的创新 PvP FPS 和 TPS 英雄射击战斗游戏<br>- 流畅的运动和枪战<br>- 令人振奋的动作，放大移动大逃杀的乐趣<br>- 植根于身临其境且不断发展的 Apex 传奇宇宙<br>- 不可预测的条件和挑战<br>- 不断推出新的传奇来测试玩家的技能<br><br>移动优先适应与创新<br>- 移动设备上的独立 Apex Legends 标题<br>- 为移动设备定制的优化 UI 和控件<br>- 独特的移动内容和游戏模式<br>- 新的传奇、地图、游戏玩法、模式、进度和现场活动<br><br>立即下载并成为 Apex 传奇！<br><br>注册并不能保证可以访问 Apex Legends™ Mobile。需要接受 (i) 发布前反馈协议。年龄限制适用。在有限地区发布中取得的游戏进度、成就、角色、角色数据和/或任何其他价值或状态指标将不会转移到全球发布。 Apex Legends Mobile 是一款受限地区的预发布软件，可能包含错误/缺陷，并按“原样”提供，没有任何明示或暗示的保证。<br><br>此应用程序：需要接受 EA 的隐私和 Cookie 政策和用户协议。需要持续的 Internet 连接（可能需要支付网络费用）。包括游戏内广告。通过第三方广告服务和分析技术收集数据（有关详细信息，请参阅隐私和 Cookie 政策）。包含指向 Internet 和社交网站的直接链接，供 13 岁以上的观众使用。允许玩家交流。包括可选的游戏内虚拟货币购买，可用于获取虚拟游戏内物品，包括随机选择的虚拟游戏内物品。该应用使用 Google Play 游戏服务。如果您不想与朋友分享您的游戏，请在安装前退出 Google Play 游戏服务。<br><br>用户协议：terms.ea.com<br>隐私和 Cookie 政策：privacy.ea.com<br>访问 help.ea.com 获取帮助或查询。<br><br>不要出售我的个人信息：https://tos.ea.com/legalapp/WEBPRIVACYCA/US/en/PC/<br><br>EA 可能会在 ea.com/service-updates 上发布 30 天通知后停用在线功能。 24:map[1:2 3:map[1:map[2:map[1:com.ea.gp.apexlegendsmobilefps 2:1 3:3]] 2:0 6:map[1:1652403311426261 2:85379530 3:2634905390] 17:map[1:0 2:map[1:zh-CN 2:1]]] 37:map[3:map[1:0 2:map[1:map[1:com.ea.gp.apexlegendsmobilefps 2:1 3:3]] 9:map[1:1652403311426261 2:85379530 3:2634905390] 31:map[1:map[1:0 2:map[1:zh-CN 2:1]]]]]] 25:map[2:map[1:提供方 3:map[2:ELECTRONIC ARTS]]] 26:0 27:组队并在多人大逃杀的下一次演变中为生存而战！ 29:0 32:0 34:reviewQuestions?doc=com.ea.gp.apexlegendsmobilefps 38:map[1:1 2:lpi 3:1] 39:reviewSummary?doc=com.ea.gp.apexlegendsmobilefps 40:map[2:map[51:allReviews?doc=com.ea.gp.apexlegendsmobilefps&sfilter=ALL]] 43:3 45:1 49:map[1:1 2:map[1:map[1:7 8:map[1:18]]]] 50:map[1:12 岁以上 2:中度暴力<br/>用户交互, 游戏内购买（含随机项目）<br/><a href="https://support.google.com/googleplay?p=appgame_ratings">了解详情</a> 3:map[-6:map[1:https://play-lh.googleusercontent.com/yQChfa9XKlaXMIYTk8w8QwChjT8_SH-_2d2SS-kesw0TLQK1nxtw54bDcoZ09freZJgKrtg4f__is-31Vg] 2:2 3:map[1:366 2:512] 6:
xhttps://play-lh.googleusercontent.com/yQChfa9XKlaXMIYTk8w8QwChjT8_SH-_2d2SS-kesw0TLQK1nxtw54bDcoZ09freZJgKrtg4f__is-31Vg] 5:中度暴力 6:用户交互, 游戏内购买（含随机项目） 8:map[1:map[1:7 8:map[1:15]]]]] 6:map[1:1 2:map[1:5 4:map[2:map[1:com.ea.gp.apexlegendsmobilefps 2:1 3:3]] 11:map[1:1652403311426261 2:85379530 3:2634905390] 16:map[1:0 2:map[1:zh-CN 2:1]]] 37:map[1:map[1:DETAILS_PAGE 2:map[1:map[1:com.ea.gp.apexlegendsmobilefps 2:1 3:3] 3:map[1:map[1:0 2:map[1:zh-CN 2:1]]]]]]] 8:1 13:getDetailsStream?doc=com.ea.gp.apexlegendsmobilefps 17:getPostAcquireDetailsStream?doc=com.ea.gp.apexlegendsmobilefps 21:popups]] 5:map[1:153] 9:map[1:18 19:map[1:map[1:1652403311426261 2:85379530 3:2634905390] 2:1]]] <nil> adada
<nil> cannot unmarshal <nil> into field 2 of type protobuf.Varint com.ea.gp.apexlegendsmobilefps ddddd
panic: cannot unmarshal <nil> into field 2 of type protobuf.Varint

goroutine 1 [running]:
main.main()
        /home/suracle/Desktop/A_go_project/googleplay/cmd/googleplay/main.go:82 +0x8e5
