### ISSUE TITLE
panic: cannot unmarshal <nil> into field 2 of type protobuf.Varint

### ISSUE THREAD

**Issue by andreroggeri** [89z/googleplay#51]
When trying to run `googleplay -a com.nu.production`

**Comment by 89z** [comment]
Works with the ARM client:

~~~
PS D:\Desktop> googleplay.exe -a com.nu.production -armeabi
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.nu.production
Title: Nubank: conta, cartão e mais
Creator: Nu
UploadDate: Apr 27, 2022
VersionString: 7.58.7-minApi26
VersionCode: 1000035249
NumDownloads: 89.815 M
Size: 138.637 MB
Files: 3
Offer: 0 USD
~~~

I will leave this open for now, as I think I should improve the error message.

**Comment by 89z** [comment]
OK I have improved the error message somewhat:

https://github.com/89z/googleplay/blob/aa8d16e20233deb06d80827f2e55cd96dd0e2a48/header.go#L100-L106

and updated the help a little:

https://github.com/89z/googleplay/blob/aa8d16e20233deb06d80827f2e55cd96dd0e2a48/cmd/googleplay/main.go#L14-L19

I will consider this good for now.
