### ISSUE TITLE
panic: Purchase required when trying to download app (after running -purchase)

### ISSUE THREAD

**Issue by adtimizer** [89z/googleplay#52]
Hello,
I'm facing an issue with downloading apk.
I've followed the instructions and getting panic: Purchase required.

performing the following:

./googleplay -e xxxxxx@gmail.com -p xxxxxx
./googleplay -d
./googleplay -a com.google.android.youtube
./googleplay -a com.google.android.youtube -purchase
./googleplay -a com.google.android.youtube -v 1529210304

getting the following:

POST https://android.googleapis.com/auth
GET https://play-fe.googleapis.com/fdfe/delivery?doc=com.google.android.youtube&vc=1529210304
panic: Purchase required

goroutine 1 [running]:
main.main()
	/Users/xxxxxxx/Downloads/newGoogleDownlaod/dirrr/googleplay/cmd/googleplay/main.go:75 +0x704
	
what am i missing?

**Comment by 89z** [comment]
That command works as expected for me:

~~~
PS C:\> googleplay -a com.google.android.youtube -v 1529210304
POST https://android.googleapis.com/auth
GET https://play-fe.googleapis.com/fdfe/delivery?doc=com.google.android.youtube&vc=1529210304
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0RiAGLLNq8zS6PYiWEuOAjnDQ9F0SpsSVEUt8Uu_cCNTahcj_V4Bv63uovRVsNQNJArsFclEcxA6Q_TQoPsTQyNza1V9b4oIClpSxwhqbyh1yoX4KRcEF2nFqRlu588VAA1hQ1bjji44s4fToTL5AuM0cPAGoQ1Esbv2-DRqNZSf9f05W4ahTDkOemuV4yKSuFZ_gReKzSm4f5mbEvY7fa4luQUiISxHPNG0O2pSDiN5QNKxpm_0Lf8JiVSzO0veG2FyuAv__aH5v6ZkBOZHupfwTMl0EIngipcUamOxRrIa3OMPdA-pLCDFxvTkLy967NR6jgcmu5LRnVz0TF4XoOxseYMcV842alf6d1Re8J_mTTauGhzzvDT1RvGFwe-9ujN8zRuLrB_8rRZZgWKIcCaWFbfPPqKuRyZIXJiBBDnqJG66GIWFA&cpn=r-Z-2shXurN66Lom
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0RZmUCgEmRK946elTT2Wht_TJDpGgWKyisYjf0Q14xgcEl7_Cg5ukP2oxRgRCh6V5YsiROsrYGqq61_cdIYRz-dc6CZBLplDKWWPCU3P2uVrf27GCm6z5KqxaR3Be4_6g1c4CKZ3x2xN6cuRvrgApOsNBBUC7ZKTImholHloJ9TH3amJ9mRs8c1skm65W2B8tyqdclhfH_ULMtrDJ8GgPTCHstKCUKxkM77210a5sNKAq-oVynftG5XP1gABFIEcVb3VKVlEb2tMnr6s6QOZ9BYzt_W2G9gD98_dAmmF5ODviLGStR6vLIyiGMEoiN_by0iOvcUsGDl39JCzIYBhM-YZkEKYKbxL17wId8REKQubRizdi5WEvoDCKex_8Zuay6FYYuWJFPCX5LsO2V_QIAwK91eurVK1wLfmVPMhQZQbFvkI_I&cpn=88bp3bFebcKFS4j4
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0Qdzj10wEH1l5bgxHM4GBsqObYBdGf54ks3wlrMMXCptXIS5Lw2xch6_kcS0xoU_N_2yhXzMmVI3e7ZNM9csjub51pV74sVbDgmUfCCLjIgfvSmBWr0yWw7CFRurcJcxFzqcz2I6YyLBa19cieLcS1AJoXxJWCiN1lss-g5OfsfUtlF-ezRiUJovgarSjfX96L1pI0v5NRtYhoRnPVCk5E72aXV5N77812K-NLCYScueQHtfFK6SF7Ta-bWLkkQAD9Qe0VwJBiLdjImT6F6mHBmQ-5kyQ_ls0D3qrk--KQKAyoWkV21eQByqSWcJ39oXL6EFd3ebEGlcBy6bEcIJ517kALK0PnYPmZ1Vihqp74zfDZVfS6EtL2byiIIpWFp7G8aPo5Awia_Ws1LkZVrv3qps-LCM0-aDpZ6uiEI6swiAGwzO1totw&cpn=EHBnKy4fAvz-_QBN
49.1%   11.076 MB       22.139 MB/s
98.9%   22.315 MB       22.299 MB/s
GET https://play.googleapis.com/download/by-token/download?token=AOTCm0Swbgmb1BXNUqC7XG_bVHsWhn5_WU-fmtOfTIxmft97GZ1gewXnPzO66EI4-LILLKxLdUfULHNHPyg8WFoWRw_3KRH5VLrfclIOwE4HmTeqvYrhKk2p9cnvTlqvVqmZPqQNunmlJK2i8LI3YR9je-IpTXs8UBXdeYqASm2DrWfnoivombxFZ5SXXRgwMyCI7p-2UqbJyYvwdscR7ujdHhljYhdLFsnJp9JbnrYYB_YRJP4gMjF7ZoP89hfci5Ge0gsmP_6fUU7EIJQISCzqWjTvGU48lQid5kw4_FK4X6Q6bPf8VVqxgIOd6Q10hEs-iR8T6aA_LW_XMFGF8qJhxdm-hH7sBe8blitCYigQ2rA_55dcM9akiCY-auharFS-Ny49gjmc_Us94cjQ91iXmY_en3QAJHotUsOEUYv4&cpn=91YfyqEokD-efs7P
52.2%   10.600 MB       21.185 MB/s
~~~

I will need to look into this.

**Comment by 89z** [comment]
Can you try to install the YouTube app on an actual phone or emulator? Then after that, try the command again.

**Comment by adtimizer** [comment]
@89z tried it (and tried also two other apps) without any luck.
using mac with m1 chip and tried also on a mac with intel cpu.

**Comment by 89z** [comment]
Can you try this program, and attach `delivery.txt` in a response comment:

~~~go
package main

import (
   "encoding/json"
   "github.com/89z/format/protobuf"
   "net/http"
   "net/url"
   "os"
   gp "github.com/89z/googleplay"
)

func main() {
   cache, err := os.UserCacheDir()
   if err != nil {
      panic(err)
   }
   token, err := gp.OpenToken(cache, "googleplay/token.json")
   if err != nil {
      panic(err)
   }
   device, err := gp.OpenDevice(cache, "googleplay/x86.json")
   if err != nil {
      panic(err)
   }
   header, err := token.Header(device)
   if err != nil {
      panic(err)
   }
   var req http.Request
   req.Header = header.Header
   req.URL = new(url.URL)
   req.URL.Host = "play-fe.googleapis.com"
   req.URL.Path = "/fdfe/delivery"
   val := make(url.Values)
   val["doc"] = []string{"com.google.android.youtube"}
   val["vc"] = []string{"1529210304"}
   req.URL.RawQuery = val.Encode()
   req.URL.Scheme = "https"
   res, err := new(http.Transport).RoundTrip(&req)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   mes, err := protobuf.Decode(res.Body)
   if err != nil {
      panic(err)
   }
   file, err := os.Create("delivery.txt")
   if err != nil {
      panic(err)
   }
   defer file.Close()
   json.NewEncoder(file).Encode(mes)
}
~~~

**Comment by adtimizer** [comment]
{"1":{"21":{"1":3}},"5":{"1":607},"9":{"1":18,"19":{"1":{"1":1652385914322491,"2":182434958,"3":4077330452},"2":1}}}

**Comment by 89z** [comment]
Sorry, I think I am out of ideas. If you have a Google account that you don't mind sharing, then you can email me the Email and Password. Otherwise, you can try some other programs to see if they work. This is one that I have used in the past:

https://raccoon.onyxbits.de/apk-downloader

**Comment by adtimizer** [comment]
adding to the above, i've tried it also with windows machine and using 2FA (with app password) and it allows to download apps but only ones that were purchased in the past. apps that weren't installed on my device in the past can't be installed.

**Comment by 89z** [comment]
> apps that weren't installed on my device in the past can't be installed

This tool isn't, and never was for the purpose of installing apps. This tool is only for getting app information, and downloading apps.

**Comment by adtimizer** [comment]
@89z what i mean is that the purchase function doesn't work for me.
I'm not trying to install (i meant download). sorry for the confusion.

**Comment by 89z** [comment]
Please provide example of working command, and example of failing command.

**Comment by 89z** [comment]
The ARM64 options have been removed. Please try again with current master commit.

**Comment by 89z** [comment]
closing for lack of response
