### ISSUE TITLE
I am not able to login to the playstore

### ISSUE THREAD

**Issue by Arshit007** [89z/googleplay#53]
It is giving me 'Security check is needed, try to visit https://accounts.google.com/b/0/DisplayUnlockCaptcha to unlock, or setup an app-specific password' again and again

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/47

**Comment by 89z** [comment]
Works for me with current master:

~~~
PS C:\> googleplay -e MY_EMAIL -p MY_PASSWORD
POST https://android.googleapis.com/auth
Create C:\Users\Steven\AppData\Local\googleplay\token.json
~~~

**Comment by 89z** [comment]
closing for lack of response
