### ISSUE TITLE
How to find game support device platform?

### ISSUE THREAD

**Issue by MrLuoXuan** [89z/googleplay#54]
Hello, I have a question about how to find game support device platform.
For example package com.kakaogames.twodin, I tried armeabi arm64 and x86, can't get version from google.
Can you get version info from this package name ?

**Comment by 89z** [comment]
I found a fix for this, but it will take a while to implement. Please be patient.

**Comment by 89z** [comment]
This should be fixed now:

~~~
PS C:\> googleplay -a com.kakaogames.twodin -arm64
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.kakaogames.twodin
Title: 奧丁 : 神叛
Creator: Kakao Games Corp.
UploadDate: May 9, 2022
VersionString: 1.2.5
VersionCode: 19
NumDownloads: 246.668 K
Size: 149.634 MB
Files: 5
Offer: 0 USD
~~~

Note you probably need to run `googleplay -d -arm64` one time as well.

**Comment by 89z** [comment]
also, please star this repo if its helpful
