### ISSUE TITLE
How to download x86 apk?

### ISSUE THREAD

**Issue by druphliu** [89z/googleplay#56]
Hello, I have a question about how to download game x86 apk?You only provide armeabi and ARM64 for download, but there are x86 x86_64 platforms, how to download?

**Comment by muzzyrost** [comment]
To download x86 versions you don't need to use any keys. But remember that not all apps have x86 versions.

**Comment by 89z** [comment]
please provide example app

**Comment by 89z** [comment]
If youre interested, I have improved the platform selection:

~~~
Usage of C:\Users\Steven\go\bin\googleplay.exe:
  -a string
        app
  -d    create device
  -email string
        your email
  -p int
        0 x86
        1 armeabi-v7a
        2 arm64-v8a
  -password string
        your password
  -purchase
        Purchase app. Only needs to be done once per Google account.
  -s    single APK
  -v uint
        version
  -verbose
        dump requests
~~~
