### ISSUE TITLE
wrong ABI

### ISSUE THREAD

**Issue by umair-rhl** [89z/googleplay#57]
I am trying to download com.huuuge.domino , but it returns:
```
panic: wrong ABI
goroutine 1 [running]:
main.main()
        /home/umair/Desktop/googleplay/cmd/googleplay/main.go:80 +0x74c
```

I thought it was an issue with the flags and I might have to use proper flags, I tried the arm64 one which returns:
```
panic: open /home/umair/.cache/googleplay/arm64.json: no such file or directory
```

I tried running the tool with the -d flag and mentioning arm64 which returned:
```
Sleeping 4s for server to process
Create /home/umair/.cache/googleplay/x86.json
```

I believe the proper file for x86 is not getting created in my case, can you please see if this is some code issue or something is wrong with my code?

**Comment by umair-rhl** [comment]
I realized it was a mistake on my end. I was missing a - before arm64. Sorry for the trouble and great job with the tool :)

**Comment by 89z** [comment]
If my tool is helpful, please star the repo
