### ISSUE TITLE
About aas_et token

### ISSUE THREAD

**Issue by Walkyst** [89z/googleplay#6]
Tried to search how long `aas_et` token is live before it needs to be updated, but no luck or it can be obtained once and it forever until password is changed on google account?

**Comment by 89z** [comment]
Sorry I dont really have an answer to that, as I havent done testing on it. Typically you will generate the token:

~~~
googleplay -e EMAIL -p PASSWORD
~~~

and it should last quite a while, I would guess at least one month. However in the process of development, I was creating several GSF IDs:

~~~
googleplay -d
~~~

and I noticed that if you create too many (like 10 in a row), then you are forced to create a new token. However in general use, a user will create one token, and one GSF ID, then use those with future requests. So as long as you are not repeatedly creating new devices (you should not need to do that), then token should last long time. If you do you own testing and get more information, I can add your findings to my notes. However I do not have interest in doing my own testing, so I will close this for now. If you have other concerns I can reopen, thanks!
