### ISSUE TITLE
New 'uses-feature' for config.go

### ISSUE THREAD

**Issue by muzzyrost** [89z/googleplay#61]
Hi! I'm trying to research few unaviable apps. 

For **com.imangi.templerun2** next issue with both -arm64 and -armeabi

All required features in AndroidManifest declared in config.go but it won't get version code.

Example for **com.lensa.app**

Looks like it requides **android.hardware.camera.any, android.hardware.faketouch and uses-gl-es: '0x30002'**

Example for **com.sygic.aura**

It required **android.hardware.location.network**

Example for **com.hp.printercontrol**

It required: **android.hardware.location.network**, **android.hardware.faketouch**

**Comment by muzzyrost** [comment]
Adding this features to config.go help me download this apps.

My additional list for now:
```
      "android.hardware.location.network",
      "android.hardware.location.gps",
      "android.hardware.camera.any",
      "android.hardware.faketouch",
      "android.hardware.touchscreen.multitouch",
      "android.hardware.touchscreen.multitouch.distinct",
      "android.software.managed_users",
      "android.software.live_wallpaper",
      "android.hardware.sensor.gyroscope",
      "com.nvidia.feature.shield",
      "android.hardware.nfc",
      "android.hardware.camera.front",
      "android.hardware.camera.flash",
      "android.hardware.camera2",
      "android.hardware.camera.front.autofocus",
```

**Comment by muzzyrost** [comment]
Anyway I can't get next popular apps:
```com.instagram.android
com.olzhas.carparking.multyplayer
app.source.getcontact
com.illumix.fnafar
com.MobileSimulated.caseforst
com.tgc.sky.android
```

**Comment by 89z** [comment]
sorry for the trouble, but I am going to have to close this.

I need each app posted to its own issue, as I need to decide for each app, if its something I am willing to support. I don't just blindly accept any app, I have certain criteria. If you can please post separate issue for each app, we can continue the discussion. Thank you!

**Comment by 89z** [comment]
This is done, see linked issues for more info

note I am refusing to support some of the request apps

For any app over 512 MB, I require payment to support.

**Comment by muzzyrost** [comment]
Thanks 🙏
