### ISSUE TITLE
x86_64 support

### ISSUE THREAD

**Issue by kotori2** [89z/googleplay#62]
Maybe by changing the command line flag to `-arch [armeabi/arm64/x86/x86_64]`

**Comment by 89z** [comment]
Can you clarify why this is needed? Have you found an app, that works with x86_64, but not x86?

Most physical devices are ARM, so the only reason x86 exists, is so that I can download apps to use with emulator. Can you explain your use case?

**Comment by kotori2** [comment]
Because since Android 12 Google removed 32bit support for AVD manager. All images in AVD manager are now 64bit only. 
<img width="804" alt="image" src="https://user-images.githubusercontent.com/17663689/169298427-574e756c-8f16-4b4c-8da9-57ee59fda922.png">

**Comment by 89z** [comment]
If you have an `x86` app, you can use it with an `x86_64` emulator.

I just tested this by install the `x86` version of `kr.sira.metal` app, onto emulator Android 7 Google APIs `x86_64`. Are you able to do this?

**Comment by kotori2** [comment]
> If you have an `x86` app, you can use it with an `x86_64` emulator.
> 
> I just tested this by install the `x86` version of `kr.sira.metal` app, onto emulator Android 7 Google APIs `x86_64`. Are you able to do this?

Unfortunately no. Google removed 32bit runtime from 64bit AVD images since Android 12.

**Comment by 89z** [comment]
> Google removed 32bit runtime from 64bit AVD images since Android 12.

whaa? those bastards!

**Comment by 89z** [comment]
OK, can you clarify why you must use Android 12? Why is lower version not acceptable? Sorry for the extra questions, but since I will be the person maintaining this, it needs to be justified.

**Comment by 89z** [comment]
If you're interested, I have improved the platform selection:

~~~
Usage of C:\Users\Steven\go\bin\googleplay.exe:
  -a string
        app
  -d    create device
  -email string
        your email
  -p int
        0 x86
        1 armeabi-v7a
        2 arm64-v8a
  -password string
        your password
  -purchase
        Purchase app. Only needs to be done once per Google account.
  -s    single APK
  -v uint
        version
  -verbose
        dump requests
~~~

**Comment by 89z** [comment]
closing for lack of response
