### ISSUE TITLE
download the apk to an specific folder

### ISSUE THREAD

**Issue by BrunoFischerGermany** [89z/googleplay#7]
Hello 89z, 

thanks for your cool programm. 

But i don't know to download the apk to an specific folder. 

I have an Database with the PlayStoreID (e.g. org.wikipedia or com.bitdefender.security). I want now to download it with 1 or 2 Lines in the terminal. 

How i can create it?

I make googleplay -e email@gmail.com -p PASSWORD -d -a "org.wikipedia"

i Think aapt dump but i dont know the path to folder an the name of the apk. best where -a -{Value}.apk, right?

Thanks for Your Help!!

**Comment by 89z** [comment]
Please just follow the instruction [1] on the main page, its pretty simple. First you create a token. This is a one time process, so you dont use these flags with every command:

~~~
googleplay -e EMAIL -p PASSWORD
~~~

Then you create a device. Again this is a one time process, so you do not use this flag with every command:

~~~
googleplay -d
~~~

Then get the version code:

~~~
PS C:\> googleplay -a org.wikipedia
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/details?doc=org.wikipedia
&{InstallationSize:12.782 MB NumDownloads:55.768 M Offer:0.00 USD
Title:Wikipedia VersionCode:50388 VersionString:2.7.50388-r-2021-12-02}
~~~

Then purchase:

~~~
googleplay -a org.wikipedia -purchase
~~~

Then download:

~~~
googleplay -a org.wikipedia -v 50388
~~~

Again, this is all laid out on the main page, so I am not happy that you are posting this issue.

1. https://github.com/89z/googleplay#tool-examples

**Comment by BrunoFischerGermany** [comment]
Hello 89z,

thank you for the much info. I did not want to make you unhappy :( Now everything has become clear to me. Thank you! I thought there is only 1 command and it downloads the APK. 

But a switch where I can load the AKP I have not found. Right?

Great would be a -o /home/user/ or a C:\Users\Documents\.

Is something like that planned?

**Comment by 89z** [comment]
You want to control the output folder?

**Comment by BrunoFischerGermany** [comment]
Yes. Because i use it to automated download apks, when updated. I have an database with the timestamps. 
With the Database i have an folder structur for the different apk versions.  

before run googleplay i can navigate to the right folder (e.g. cd /home/user/) thats right. But a contol to the folder would be nice. 

by the way. in my googlelogin i have now the Oneplus-A0001-device. When im running the App (https://play.google.com/store/apps/details?id=com.xiaomi.smarthome.tv.global2) nothing is downloaded. I purchased it, it is shown, but VersionCode is 0. 

googleplay -a com.xiaomi.smarthome.tv.global2
POST https://android.clients.google.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.xiaomi.smarthome.tv.global2
&{InstallationSize:0.000 B NumDownloads:29.222 k Offer:0.00 EUR Title: VersionCode:0 VersionString:} 

On The PlayStore Website: "This item is not compatible with your device."  <-- Oneplus-A001

Any Idea?

**Comment by 89z** [comment]
https://github.com/89z/googleplay/issues/8

**Comment by 89z** [comment]
OK this should be fixed now. Example command:

~~~
googleplay -a org.wikipedia -v 50388 -o hello
~~~

https://github.com/89z/googleplay/commit/76f71fde27acc608c838d0a19e10784f79fd1d14

**Comment by BrunoFischerGermany** [comment]
Thank You!

-o Works fine 👍👌

**Comment by BrunoFischerGermany** [comment]
I update to version 1.7.0
do you remove the switch -o ?

Greets

**Comment by 89z** [comment]
This should be fixed again, and I made another tag:

https://github.com/89z/googleplay/tree/v1.8.0

but youll need to build it yourself
