### ISSUE TITLE
panic: wrong ABI

### ISSUE THREAD

**Issue by kelvinxue** [89z/googleplay#75]
Hi,

I am trying to download binance apk and found this error

the play store url: 

https://play.google.com/store/apps/details?id=com.binance.dev

the command: 

googleplay -a com.binance.dev

The results logs:

POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.binance.dev
panic: wrong ABI

goroutine 1 [running]:
main.main()
	/home/xxx/dev/googleplay/cmd/googleplay/main.go:77 +0x6b6

Any idea?

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> googleplay -a com.binance.dev
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.binance.dev
Title: Binance: Buy BTC & 600+ Crypto
Creator: Binance Inc.
UploadDate: May 16, 2022
VersionString: 2.45.7
VersionCode: 10024507
NumDownloads: 54.188 M
Size: 155.663 MB
Files: 3
Offer: 0 USD
~~~
