### ISSUE TITLE
panic: wrong ABI

### ISSUE THREAD

**Issue by kelvinxue** [89z/googleplay#76]
Hi,

I found that the binance issue fixed quickly, thx

Then I tried this xt app I got wront ABI again

url: https://play.google.com/store/apps/details?id=com.app.xt

command: 

googleplay -a com.app.xt

results:

POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.app.xt
panic: wrong ABI

goroutine 1 [running]:
main.main()
	/home/xxx/dev/googleplay/cmd/googleplay/main.go:77 +0x6b6

That is wired

**Comment by 89z** [comment]
please star this repo to continue, thank you

**Comment by kelvinxue** [comment]
already starred, nice project

**Comment by 89z** [comment]
Fixed:

~~~
PS C:\> googleplay -a com.app.xt
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.app.xt
Title: XT.COM - Buy & sell Bitcoin
Creator: XT.COM Inc.
UploadDate: May 13, 2022
VersionString: 3.8.2
VersionCode: 3008002
NumDownloads: 276.106 K
Size: 32.632 MB
Files: 3
Offer: 0 USD
~~~
