### ISSUE TITLE
Last version is broken

### ISSUE THREAD

**Issue by muzzyrost** [89z/googleplay#77]
```
googleplay -a org.telegram.messenger -p 1 -u 0
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=org.telegram.messenger
panic: parsing time "28 \xd0\xba\xd0\xb2\xd1\x96\xd1\x82. 2022 \xd1\x80." as "Jan 2, 2006": cannot parse "28 \xd0\xba\xd0\xb2\xd1\x96\xd1\x82. 2022 \xd1\x80." as "Jan"
```

**Comment by 89z** [comment]
Works for me:

~~~
PS D:\Desktop> googleplay -a org.telegram.messenger -p 1 -u 0
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=org.telegram.messenger
Title: Telegram
Creator: Telegram FZ-LLC
UploadDate: 2022-04-28
VersionString: 8.7.4
VersionCode: 26363
NumDownloads: 1.213 B
Size: 48.331 MB
File: APK
Offer: 0 USD
~~~

try again with current master

**Comment by 89z** [comment]
Oh I see, is a language issue:

~~~
28 квіт. 2022 р.
~~~

**Comment by 89z** [comment]
For now, you can just remove these lines:

https://github.com/89z/googleplay/blob/7b6d08ec5802b553e3b4ae20bca8259f8c512dca/cmd/googleplay/googleplay.go#L34-L38

I want this code to remain, I will see if I can think of a permanent fix. Stand by.

**Comment by 89z** [comment]
Can you please run this code, and post the resulting file?

~~~go
package main

import (
   "github.com/89z/googleplay"
   "net/http"
   "net/url"
   "os"
)

func main() {
   cache, err := os.UserCacheDir()
   if err != nil {
      panic(err)
   }
   token, err := googleplay.OpenToken(cache, "googleplay/token.json")
   if err != nil {
      panic(err)
   }
   device, err := googleplay.OpenDevice(cache, "googleplay/x86.json")
   if err != nil {
      panic(err)
   }
   head, err := token.Header(device.AndroidID, 0)
   if err != nil {
      panic(err)
   }
   var req http.Request
   req.Header = make(http.Header)
   head.SetAuth(req.Header)
   head.SetDevice(req.Header)
   req.URL = new(url.URL)
   req.URL.Host = "android.clients.google.com"
   req.URL.Path = "/fdfe/details"
   val := make(url.Values)
   val["doc"] = []string{"org.telegram.messenger"}
   req.URL.RawQuery = val.Encode()
   req.URL.Scheme = "https"
   res, err := new(http.Transport).RoundTrip(&req)
   if err != nil {
      panic(err)
   }
   defer res.Body.Close()
   file, err := os.Create("org.telegram.messenger.txt")
   if err != nil {
      panic(err)
   }
   defer file.Close()
   file.ReadFrom(res.Body)
}
~~~

**Comment by muzzyrost** [comment]
Here is file, my account langusge is ukrainian:
[org.telegram.messenger.txt](https://github.com/89z/googleplay/files/8747998/org.telegram.messenger.txt)

**Comment by 89z** [comment]
OK I tested again with this one:

~~~
com.valvesoftware.android.steam.community
~~~

since its old, I am able to easily differ the `uploadDate` against the current date. However in the response I don't see any Unix time, only the string time, and only in this format:

~~~
Jun 1, 2021
~~~

rather than proper RFC 3339:

~~~
2006-01-02
~~~

So, I guess I will need to make date transformation option, with default turned off. I am going to lunch, I can fix this after lunch. Thanks for the uploaded file.

**Comment by 89z** [comment]
Ooh, I see you can change the language:

~~~
Accept-Language: uk-UA
~~~

hm...

**Comment by muzzyrost** [comment]
Google just use my profile setting. It's not a big issue, I can just change settings, but for other users may need some additional info in readme.

**Comment by 89z** [comment]
OK this should be fixed now:

https://github.com/89z/googleplay/blob/2dfb9c52b791019d24eb68448c96c5c392ced583/cmd/googleplay/googleplay.go#L18-L21

If parsing fails, then date will just use the text as is. I could add an option to force English, but I think this is good enough for now.
