### ISSUE TITLE
panic: assignment to entry in nil map

### ISSUE THREAD

**Issue by duyuphp** [89z/googleplay#78]
googleplay -device

panic: assignment to entry in nil map

goroutine 1 [running]:
github.com/89z/format/protobuf.add[...](...)
	D:/workspaces/go/pkg/mod/github.com/89z/format@v1.35.5/protobuf/private.go:12
github.com/89z/format/protobuf.Message.AddString(0x7115e0?, 0x109c88?, {0x72cff0?, 0x1?})
	D:/workspaces/go/pkg/mod/github.com/89z/format@v1.35.5/protobuf/public.go:19 +0x35c
github.com/89z/googleplay.Config.Checkin({{0x959700, 0x15, 0x15}, 0x99999, {0x953840, 0x2, 0x2}, 0x0, 0x0, 0x0, ...}, ...)
	D:/workspaces/go/src/googleplay/config.go:142 +0x10df
main.doDevice({0x72741c, 0x3})
	D:/workspaces/go/src/googleplay/cmd/googleplay/googleplay.go:100 +0xa8
main.main()
	D:/workspaces/go/src/googleplay/cmd/googleplay/main.go:57 +0x6cf

**Comment by 89z** [comment]
Sorry about the trouble

I had to update my ProtoBuf software, but I made a mistake in the code. I will try to fix it today. Until then, you can use old version:

https://github.com/89z/googleplay/releases/tag/v1.9.5

**Comment by 89z** [comment]
OK this should be fixed now

If you still have problem - let me know. Thanks
