### ISSUE TITLE
versionCode missing

### ISSUE THREAD

**Issue by kelvinxue** [89z/googleplay#84]
Hi,

I pulled the latest master branche code and try this:

$ googleplay -a com.binance.dev

then I got this error:

POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.binance.dev
panic: com.binance.dev versionCode missing
Check nativePlatform

goroutine 1 [running]:
main.main()
	/home/xxx/dev/googleplay/cmd/googleplay/main.go:88 +0x85b

Thx

**Comment by 89z** [comment]
Default platform is x86:

~~~
-p int
     nativePlatform
     0: x86
     1: armeabi-v7a
     2: arm64-v8a
~~~

In this case, the app does not offer x86 version, so you need to choose another platform:

~~~
> googleplay -a com.binance.dev -p 1
Title: Binance: Buy BTC & 600+ Crypto
Creator: Binance Inc.
UploadDate: May 26, 2022
VersionString: 2.46.5
VersionCode: 100024605
NumDownloads: 54.877 M
Size: 146.825 MB
File: APK APK APK APK
Offer: 0 USD
~~~
