### ISSUE TITLE
panic error：versionCode Missing

### ISSUE THREAD

**Issue by ezraguo-dev** [89z/googleplay#85]
Hello,

I found that googleplay did not work on downloading some APKs.  I followed your instruction to get APP details, but I got this error,
![image](https://user-images.githubusercontent.com/55737412/170947626-539d4158-886d-486a-b8cc-c1cedc0f1b00.png)

It seems like a loop, I need the APP detail to get the version code, but I also need to provide the version code to get the APP detail.

**Comment by ezraguo-dev** [comment]
This problem is similar to the closed case "versionCode missing #84". 
I tried to switch the platform from x86 to arm, but got below error information,
![image](https://user-images.githubusercontent.com/55737412/170949149-29b0127f-16f2-4378-89e1-5e4b18b68d16.png)

**Comment by yuanyal** [comment]
Hi @ezraguo-dev I got the same error: arm64-v8a.json: no such file or directory

How did you resolve it? thanks
