### ISSUE TITLE
obb can't download

### ISSUE THREAD

**Issue by duyuphp** [89z/googleplay#88]
com.netease.ma100asia obb can't download

**Comment by duyuphp** [comment]
googleplay -a com.netease.ma100asia -p 2
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.netease.ma100asia
Title: Dead by Daylight Mobile
Creator: Netease Games Global
UploadDate: 12 Mei 2022
VersionString: 1.169521.169521
VersionCode: 169521
NumDownloads: 1.324 M
Size: 2.428 GB
File: APK APK APK APK APK OBB OBB
Offer: 0 USD

apk can download ，but obb can't download

**Comment by 89z** [comment]
sorry, I don't offer free support for any item over 512 MB. If you wish to purchase support, please contact me using info in my bio. Thanks
