### ISSUE TITLE
suggestion for authentication

### ISSUE THREAD

**Issue by f4biopedro** [89z/googleplay#9]
Prompt the user for email and password.
Putting passwords in the terminal is a security issue.
Someone could search the terminal history.

**Comment by 89z** [comment]
Thank you for the suggestion. However the tool is meant to only be a demonstration of the features of the module, found here:

https://godocs.io/github.com/89z/googleplay

People who wish for some feature in the tool can implement it themself, using the existing module. If you are willing to consider a donation, I might be willing to implement the feature here.
