### ISSUE TITLE
Silence HTTP requests with flag

### ISSUE THREAD

**Issue by gendelbendel** [89z/googleplay#90]
When running:
`./googleplay -a com.google.android.youtube`

Expected output:
```    
Title: YouTube
Creator: Google LLC
UploadDate: Jun 2, 2022
VersionString: 17.22.36
VersionCode: 1529734592
NumDownloads: 11.941 B
Size: 47.277 MB
File: APK APK APK APK
Offer: 0 USD
```

Recieved output:
```
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.google.android.youtube
Title: YouTube
Creator: Google LLC
UploadDate: Jun 2, 2022
VersionString: 17.22.36
VersionCode: 1529734592
NumDownloads: 11.941 B
Size: 47.277 MB
File: APK APK APK APK
Offer: 0 USD
```

Add a flag `-q` which will silence HTTP requests from appearing in output.

**Comment by 89z** [comment]
In general, I think its a bad idea to turn off logging. The default log level is "info", which just does one line per request. "verbose" is also available, which dumps the full requests. However I have added an option to turn it off:

~~~
> googleplay -a com.google.android.youtube -log -1
Title: YouTube
Creator: Google LLC
UploadDate: Jun 2, 2022
VersionString: 17.22.36
VersionCode: 1529734592
NumDownloads: 11.941 B
Size: 47.277 MB
File: APK APK APK APK
Offer: 0 USD
~~~

Also, the request go to standard error, so you could just redirect that. I think on linux, you can do something like this:

~~~
googleplay -a com.google.android.youtube 2> /dev/null
~~~
