### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by shifoc** [89z/googleplay#92]
when I try this command

`./googleplay -email  MY_EMAIL  -password MY_PASS`

I get an error

**Comment by 89z** [comment]
works fine here:

~~~
> googleplay -email srpen6@gmail.com -password PASSWORD
POST https://android.googleapis.com/auth
Create C:\Users\Steven\googleplay\token.json
~~~

This issue has already been posted multiple times. Either review the existing issues, or if you wish to pay for support, we can continue.

**Comment by shifoc** [comment]
I managed to fix it.

Log in on the web, set up two-factor authentication, and then turn on app passwords. Now instead of logging in with your password, you should input the app password you created.

**Comment by 89z** [comment]
note for any who might visit this page. the above answer is NOT needed in all cases. For example, I do not use 2FA, and my normal password works just fine with this tool
