### ISSUE TITLE
Can't get details of PvZ2 and download it

### ISSUE THREAD

**Issue by Vitaliy100** [89z/googleplay#94]
The game has version for North America and the rest of world
I tried on both but below I will provide what I got when I tried to get row version.
When I'm trying to get details of the app it tells me check nativePlatform(the app is available for both armeabi-v7a and arm64-v8a)
```
googleplay -a com.ea.game.pvz2_row -p 1
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.ea.game.pvz2_row
panic: com.ea.game.pvz2_row versionCode missing
Check nativePlatform

goroutine 1 [running]:
main.main()
        C:/googleplay/cmd/googleplay/main.go:87 +0x830
```
When I'm trying to get the apk it fails to get one and says about geo-blocking(But I can get the app from Play Store. The app doesn't have splits that's why I have used single apk argument.)
```
googleplay -a com.ea.game.pvz2_row -v 685 -s
POST https://android.googleapis.com/auth
GET https://play-fe.googleapis.com/fdfe/delivery?doc=com.ea.game.pvz2_row&vc=685
panic: geo-blocking

goroutine 1 [running]:
main.main()
        C:/googleplay/cmd/googleplay/main.go:82 +0x83b
```

**Comment by 89z** [comment]
I was able to fix this locally, but then I realized that the size is 786 MB, if you include the OBB file.

Sorry, but I don't offer free support for anything over 512 MB. If you are willing to make a donation, I can add support for this. Otherwise good luck.

**Comment by Vitaliy100** [comment]
Game can download obb. On first launch it downloads obb(but in case you already placed one in obb folder, it compares the hash of it. If it doesn't match, it deletes it and downloads original one. But only on first launch.)

**Comment by 89z** [comment]
I am not supporting this app, as the total size is over 512 MB as I have already said. Unless you can make a donation, please respect my decision.

**Comment by 89z** [comment]
I am not supporting this app, as the total size is over 512 MB as I have already said. Unless you can make a donation, please respect my decision.

**Comment by Vitaliy100** [comment]
There seems to be the same issue with other app as well(it's less than 512 MBs). Has North American version and the version for the rest of world as well.
Talking about Plants vs. Zombies.(com.ea.game.pvzfree_row. For North American version - com.ea.game.pvzfree_na)

**Comment by 89z** [comment]
it seems you removed your comment, so I am reverting this change. I suggest in the future you don't fuck with me.

**Comment by 89z** [comment]
For my reference. Shithead was @Vitaliy100 , who has now deleted and remade the same account.
