### ISSUE TITLE
google play login failed

### ISSUE THREAD

**Issue by MrLuoXuan** [89z/googleplay#96]
When use -email -password to login, return 403!
panic: 403

**Comment by MrLuoXuan** [comment]
more detail information is below.
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
        /Users/tsir/work/qy_go_code/googleplay/cmd/googleplay/main.go:54 +0x7d0

Process finished with exit code 2

**Comment by 89z** [comment]
hey sorry I am busy with another contract - I will try to look at this soon

**Comment by 89z** [comment]
sorry again about the delay. I have not forgotten about this issue. Another client was giving me a hard time. I will look at this soon

**Comment by 89z** [comment]
OK I was finally able to test this, seems it is working correctly:

~~~
> googleplay -email EMAIL -password PASSWORD
POST https://android.googleapis.com/auth
WriteFile C:\Users\Steven\googleplay\auth.txt
~~~

I would recommend checking the notes here:

https://github.com/89z/googleplay#tool-examples

**Comment by 89z** [comment]
gonna close this. If you have an comments I can reopen - thanks
