### ISSUE TITLE
Tool broken?

### ISSUE THREAD

**Issue by umair-rhl** [89z/googleplay#97]
Hi, I wanted to know if this tool doesn't work anymore? I have been trying to get it working but it returns with a 403 forbidden error every time we try to log in:

root@wave2:~/app-wave2/googleplay/cmd/googleplay# ./googleplay -email somerandomemail@gmail.com -password 12345
POST https://android.googleapis.com/auth
panic: 403 Forbidden

goroutine 1 [running]:
main.main()
        /root/app-wave2/googleplay/cmd/googleplay/main.go:54 +0x7d0
        

I went through the closed issues but realized all of them were closed since the tool is working on your end but I think it's most likely because of the saved token file. Can you try running it on a VPS and see if it works? If needed I'll be happy to let you use my VPS for the same.

**Comment by umair-rhl** [comment]
also are you sure this has nothing to do with the tool?
https://myaccount.google.com/lesssecureapps , google doesn't allows usage of credentials to third party apps anymore

**Comment by 89z** [comment]
https://github.com/89z/googleplay#issues

**Comment by owais-redhunt** [comment]
@89z Does this tool still work perfectly on your end because it is broken for some people I know.
