### ISSUE TITLE
Can you get package com.amazon.kindle detail ?

### ISSUE THREAD

**Issue by fleetof** [89z/googleplay#98]
```
./googleplay -a com.amazon.kindle -p 2
POST https://android.googleapis.com/auth
GET https://android.clients.google.com/fdfe/details?doc=com.amazon.kindle
panic: uploadDate not found, try another platform

goroutine 1 [running]:
main.main()
	/googleplay/cmd/googleplay/main.go:81 +0x7a5
```

same as `jp.naver.line.android`, `com.zhiliaoapp.musically`

**Comment by 89z** [comment]
https://github.com/89z/googleplay#issues

**Comment by cativo** [comment]
This is an issue with the platform, you need to specify the right platform for the app, for example `armeabi-v7a` as follows : 
` .\googleplay -a COM.APP.SAMPLE -device -p 1` 

if it works then good otherwise use a different platform from the list below

  -p int
        nativePlatform
        1: armeabi-v7a
        2: arm64-v8a
        0: x86

**Comment by 89z** [comment]
I have removed the previous comment from @cativo. The reason I didn't answer the question, is explained by the link I put. If you comment like that again, you will be banned.

**Comment by cativo** [comment]
@89z it is up to you if you don't want to offer support, but leave it to the community to help each others and then the ones whom are willing to support you will do. You did not offer support thus I believe I am free to comment if I can help.

Don't force people to support you while you are offering this project as an open source. They will do by nature when possible.
This way no one will be offer you any support.

**Comment by 89z** [comment]
> leave it to the community to help each others and then the ones whom are willing to support you will do.

No. If they help each other, then I don't get any money. I am in serious financial need, so your actions are actively hurting me.

> You did not offer support thus I believe I am free to comment if I can help.

Nope. This is my repo, so you can only comment if I allow it.

> Don't force people to support you while you are offering this project as an open source.

The source code is free. Support is not free. I am not forcing anyone to pay. However if they want help, then they either need to pay, or get help somewhere else. I am locking this issue, as I don't want to see any more comments. @cativo, this is your final warning.
