### ISSUE TITLE
play_test.go does have undeclared variables

### ISSUE THREAD

**Issue by EMREOYUN** [89z/googleplay#99]
From the line 9 in play_test.go
`func Test_Auth(t *testing.T) {
   auth, err := New_Auth(email, password)
   if err != nil {
      t.Fatal(err)`

Both `email` and `password` are undeclared in the file

**Comment by 89z** [comment]
This is intentional. Those are my private account details. If you have another way to do it, I will consider it

**Comment by 89z** [comment]
https://github.com/89z/googleplay#issues

**Comment by EMREOYUN** [comment]
> This is intentional. Those are my private account details. If you have another way to do it, I will consider it

You can declare empty string to it and you can comment to fill it with your details but you will not consider it without payment, I guess. So I will left this comment to other users.
